(ns demo.commons.intrinio.indices.nasdaq)

(def hundred
  [{:ticker "AAPL"}
   {:ticker "ADBE"}
   {:ticker "ADI"}
   {:ticker "ADP"}
   {:ticker "ADSK"}
   {:ticker "ALGN"}
   {:ticker "ALXN"}
   {:ticker "AMAT"}
   {:ticker "AMD"}
   {:ticker "AMGN"}
   {:ticker "AMZN"}
   {:ticker "ANSS"}
   {:ticker "ASML"}
   {:ticker "ATVI"}
   {:ticker "AVGO"}
   {:ticker "BIDU"}
   {:ticker "BIIB"}
   {:ticker "BKNG"}
   {:ticker "BMRN"}
   {:ticker "CDNS"}
   {:ticker "CDW"}
   {:ticker "CERN"}
   {:ticker "CHKP"}
   {:ticker "CHTR"}
   {:ticker "CMCSA"}
   {:ticker "COST"}
   {:ticker "CPRT"}
   {:ticker "CSCO"}
   {:ticker "CSX"}
   {:ticker "CTAS"}
   {:ticker "CTSH"}
   {:ticker "CTXS"}
   {:ticker "DLTR"}
   {:ticker "DOCU"}
   {:ticker "DXCM"}
   {:ticker "EA"}
   {:ticker "EBAY"}
   {:ticker "EXC"}
   {:ticker "EXPE"}
   {:ticker "FAST"}
   {:ticker "FB"}
   {:ticker "FISV"}
   {:ticker "FOX"}
   {:ticker "FOXA"}
   {:ticker "GILD"}
   {:ticker "GOOG"}
   {:ticker "GOOGL"}
   {:ticker "IDXX"}
   {:ticker "ILMN"}
   {:ticker "INCY"}
   {:ticker "INTC"}
   {:ticker "INTU"}
   {:ticker "ISRG"}
   {:ticker "JD"}
   {:ticker "KDP"}
   {:ticker "KHC"}
   {:ticker "KLAC"}
   {:ticker "LBTYA"}
   {:ticker "LBTYK"}
   {:ticker "LRCX"}
   {:ticker "LULU"}
   {:ticker "MAR"}
   {:ticker "MCHP"}
   {:ticker "MDLZ"}
   {:ticker "MELI"}
   {:ticker "MNST"}
   {:ticker "MRNA"}
   {:ticker "MSFT"}
   {:ticker "MU"}
   {:ticker "MXIM"}
   {:ticker "NFLX"}
   {:ticker "NTES"}
   {:ticker "NVDA"}
   {:ticker "NXPI"}
   {:ticker "ORLY"}
   {:ticker "PAYX"}
   {:ticker "PCAR"}
   {:ticker "PDD"}
   {:ticker "PEP"}
   {:ticker "PYPL"}
   {:ticker "QCOM"}
   {:ticker "REGN"}
   {:ticker "ROST"}
   {:ticker "SBUX"}
   {:ticker "SGEN"}
   {:ticker "SIRI"}
   {:ticker "SNPS"}
   {:ticker "SPLK"}
   {:ticker "SWKS"}
   {:ticker "TCOM"}
   {:ticker "TMUS"}
   {:ticker "TSLA"}
   {:ticker "TTWO"}
   {:ticker "TXN"}
   {:ticker "ULTA"}
   {:ticker "VRSK"}
   {:ticker "VRSN"}
   {:ticker "VRTX"}
   {:ticker "WBA"}
   {:ticker "WDAY"}
   {:ticker "XEL"}
   {:ticker "XLNX"}
   {:ticker "ZM"}])

(def composite
  [{:ticker "AACG"}
   {:ticker "AACQ"}
   {:ticker "AAL"}
   {:ticker "AAME"}
   {:ticker "AAOI"}
   {:ticker "AAON"}
   {:ticker "AAPL"}
   {:ticker "AAWW"}
   {:ticker "AAXN"}
   {:ticker "ABCB"}
   {:ticker "ABCL"}
   {:ticker "ABCM"}
   {:ticker "ABEO"}
   {:ticker "ABIO"}
   {:ticker "ABMD"}
   {:ticker "ABNB"}
   {:ticker "ABST"}
   {:ticker "ABTX"}
   {:ticker "ABUS"}
   {:ticker "ACAD"}
   {:ticker "ACAM"}
   {:ticker "ACBI"}
   {:ticker "ACCD"}
   {:ticker "ACER"}
   {:ticker "ACET"}
   {:ticker "ACEV"}
   {:ticker "ACGL"}
   {:ticker "ACHC"}
   {:ticker "ACHV"}
   {:ticker "ACIA"}
   {:ticker "ACIU"}
   {:ticker "ACIW"}
   {:ticker "ACLS"}
   {:ticker "ACMR"}
   {:ticker "ACNB"}
   {:ticker "ACOR"}
   {:ticker "ACRS"}
   {:ticker "ACRX"}
   {:ticker "ACST"}
   {:ticker "ACTC"}
   {:ticker "ACTG"}
   {:ticker "ADAP"}
   {:ticker "ADBE"}
   {:ticker "ADES"}
   {:ticker "ADI"}
   {:ticker "ADIL"}
   {:ticker "ADMA"}
   {:ticker "ADMP"}
   {:ticker "ADMS"}
   {:ticker "ADOC"}
   {:ticker "ADP"}
   {:ticker "ADPT"}
   {:ticker "ADSK"}
   {:ticker "ADTN"}
   {:ticker "ADTX"}
   {:ticker "ADUS"}
   {:ticker "ADV"}
   {:ticker "ADVM"}
   {:ticker "ADXN"}
   {:ticker "ADXS"}
   {:ticker "AEGN"}
   {:ticker "AEHL"}
   {:ticker "AEHR"}
   {:ticker "AEIS"}
   {:ticker "AEMD"}
   {:ticker "AEP"}
   {:ticker "AERI"}
   {:ticker "AESE"}
   {:ticker "AEY"}
   {:ticker "AEYE"}
   {:ticker "AEZS"}
   {:ticker "AFIB"}
   {:ticker "AFIN"}
   {:ticker "AFMD"}
   {:ticker "AFYA"}
   {:ticker "AGBA"}
   {:ticker "AGC"}
   {:ticker "AGEN"}
   {:ticker "AGFS"}
   {:ticker "AGIO"}
   {:ticker "AGLE"}
   {:ticker "AGMH"}
   {:ticker "AGNC"}
   {:ticker "AGRX"}
   {:ticker "AGTC"}
   {:ticker "AGYS"}
   {:ticker "AHAC"}
   {:ticker "AHCO"}
   {:ticker "AHPI"}
   {:ticker "AIH"}
   {:ticker "AIHS"}
   {:ticker "AIKI"}
   {:ticker "AIMC"}
   {:ticker "AIRG"}
   {:ticker "AIRT"}
   {:ticker "AKAM"}
   {:ticker "AKBA"}
   {:ticker "AKER"}
   {:ticker "AKRO"}
   {:ticker "AKTS"}
   {:ticker "AKTX"}
   {:ticker "AKU"}
   {:ticker "AKUS"}
   {:ticker "ALAC"}
   {:ticker "ALBO"}
   {:ticker "ALCO"}
   {:ticker "ALDX"}
   {:ticker "ALEC"}
   {:ticker "ALGM"}
   {:ticker "ALGN"}
   {:ticker "ALGS"}
   {:ticker "ALGT"}
   {:ticker "ALIM"}
   {:ticker "ALJJ"}
   {:ticker "ALKS"}
   {:ticker "ALLK"}
   {:ticker "ALLO"}
   {:ticker "ALLT"}
   {:ticker "ALNA"}
   {:ticker "ALNY"}
   {:ticker "ALOT"}
   {:ticker "ALPN"}
   {:ticker "ALRM"}
   {:ticker "ALRN"}
   {:ticker "ALRS"}
   {:ticker "ALSK"}
   {:ticker "ALT"}
   {:ticker "ALTA"}
   {:ticker "ALTM"}
   {:ticker "ALTR"}
   {:ticker "ALVR"}
   {:ticker "ALXN"}
   {:ticker "ALXO"}
   {:ticker "ALYA"}
   {:ticker "AMAL"}
   {:ticker "AMAT"}
   {:ticker "AMBA"}
   {:ticker "AMCI"}
   {:ticker "AMCX"}
   {:ticker "AMD"}
   {:ticker "AMED"}
   {:ticker "AMEH"}
   {:ticker "AMGN"}
   {:ticker "AMHC"}
   {:ticker "AMKR"}
   {:ticker "AMNB"}
   {:ticker "AMOT"}
   {:ticker "AMPH"}
   {:ticker "AMRB"}
   {:ticker "AMRH"}
   {:ticker "AMRK"}
   {:ticker "AMRN"}
   {:ticker "AMRS"}
   {:ticker "AMSC"}
   {:ticker "AMSF"}
   {:ticker "AMST"}
   {:ticker "AMSWA"}
   {:ticker "AMTB"}
   {:ticker "AMTBB"}
   {:ticker "AMTI"}
   {:ticker "AMTX"}
   {:ticker "AMWD"}
   {:ticker "AMYT"}
   {:ticker "AMZN"}
   {:ticker "ANAB"}
   {:ticker "ANAT"}
   {:ticker "ANCN"}
   {:ticker "ANDA"}
   {:ticker "ANDE"}
   {:ticker "ANGI"}
   {:ticker "ANGO"}
   {:ticker "ANIK"}
   {:ticker "ANIP"}
   {:ticker "ANIX"}
   {:ticker "ANNX"}
   {:ticker "ANPC"}
   {:ticker "ANSS"}
   {:ticker "ANTE"}
   {:ticker "ANY"}
   {:ticker "AOSL"}
   {:ticker "AOUT"}
   {:ticker "APA"}
   {:ticker "APDN"}
   {:ticker "APEI"}
   {:ticker "APEN"}
   {:ticker "APHA"}
   {:ticker "API"}
   {:ticker "APLS"}
   {:ticker "APLT"}
   {:ticker "APM"}
   {:ticker "APOG"}
   {:ticker "APOP"}
   {:ticker "APPF"}
   {:ticker "APPN"}
   {:ticker "APPS"}
   {:ticker "APRE"}
   {:ticker "APTO"}
   {:ticker "APTX"}
   {:ticker "APVO"}
   {:ticker "APWC"}
   {:ticker "APXT"}
   {:ticker "APYX"}
   {:ticker "AQB"}
   {:ticker "AQMS"}
   {:ticker "AQST"}
   {:ticker "ARAV"}
   {:ticker "ARAY"}
   {:ticker "ARCB"}
   {:ticker "ARCE"}
   {:ticker "ARCT"}
   {:ticker "ARDS"}
   {:ticker "ARDX"}
   {:ticker "AREC"}
   {:ticker "ARGX"}
   {:ticker "ARKR"}
   {:ticker "ARLP"}
   {:ticker "ARNA"}
   {:ticker "AROW"}
   {:ticker "ARPO"}
   {:ticker "ARQT"}
   {:ticker "ARRY"}
   {:ticker "ARTL"}
   {:ticker "ARTNA"}
   {:ticker "ARTW"}
   {:ticker "ARVN"}
   {:ticker "ARWR"}
   {:ticker "ARYA"}
   {:ticker "ASLN"}
   {:ticker "ASMB"}
   {:ticker "ASML"}
   {:ticker "ASND"}
   {:ticker "ASO"}
   {:ticker "ASPS"}
   {:ticker "ASPU"}
   {:ticker "ASRT"}
   {:ticker "ASRV"}
   {:ticker "ASTC"}
   {:ticker "ASTE"}
   {:ticker "ASUR"}
   {:ticker "ASYS"}
   {:ticker "ATAX"}
   {:ticker "ATCX"}
   {:ticker "ATEC"}
   {:ticker "ATEX"}
   {:ticker "ATHA"}
   {:ticker "ATHE"}
   {:ticker "ATHX"}
   {:ticker "ATIF"}
   {:ticker "ATLC"}
   {:ticker "ATLO"}
   {:ticker "ATNF"}
   {:ticker "ATNI"}
   {:ticker "ATNX"}
   {:ticker "ATOM"}
   {:ticker "ATOS"}
   {:ticker "ATRA"}
   {:ticker "ATRC"}
   {:ticker "ATRI"}
   {:ticker "ATRO"}
   {:ticker "ATRS"}
   {:ticker "ATSG"}
   {:ticker "ATVI"}
   {:ticker "ATXI"}
   {:ticker "AUB"}
   {:ticker "AUBN"}
   {:ticker "AUDC"}
   {:ticker "AUPH"}
   {:ticker "AUTL"}
   {:ticker "AUTO"}
   {:ticker "AUVI"}
   {:ticker "AVAV"}
   {:ticker "AVCO"}
   {:ticker "AVCT"}
   {:ticker "AVDL"}
   {:ticker "AVEO"}
   {:ticker "AVGO"}
   {:ticker "AVGR"}
   {:ticker "AVID"}
   {:ticker "AVIR"}
   {:ticker "AVNW"}
   {:ticker "AVO"}
   {:ticker "AVRO"}
   {:ticker "AVT"}
   {:ticker "AVXL"}
   {:ticker "AWH"}
   {:ticker "AWRE"}
   {:ticker "AXAS"}
   {:ticker "AXDX"}
   {:ticker "AXGN"}
   {:ticker "AXLA"}
   {:ticker "AXNX"}
   {:ticker "AXSM"}
   {:ticker "AXTI"}
   {:ticker "AY"}
   {:ticker "AYLA"}
   {:ticker "AYRO"}
   {:ticker "AYTU"}
   {:ticker "AZN"}
   {:ticker "AZPN"}
   {:ticker "AZRX"}
   {:ticker "AZYO"}
   {:ticker "BAND"}
   {:ticker "BANF"}
   {:ticker "BANR"}
   {:ticker "BASI"}
   {:ticker "BATRA"}
   {:ticker "BATRK"}
   {:ticker "BBBY"}
   {:ticker "BBCP"}
   {:ticker "BBGI"}
   {:ticker "BBI"}
   {:ticker "BBIG"}
   {:ticker "BBIO"}
   {:ticker "BBQ"}
   {:ticker "BBSI"}
   {:ticker "BCBP"}
   {:ticker "BCDA"}
   {:ticker "BCEL"}
   {:ticker "BCLI"}
   {:ticker "BCML"}
   {:ticker "BCOR"}
   {:ticker "BCOV"}
   {:ticker "BCOW"}
   {:ticker "BCPC"}
   {:ticker "BCRX"}
   {:ticker "BCTG"}
   {:ticker "BCYC"}
   {:ticker "BDGE"}
   {:ticker "BDSI"}
   {:ticker "BDSX"}
   {:ticker "BDTX"}
   {:ticker "BEAM"}
   {:ticker "BEAT"}
   {:ticker "BECN"}
   {:ticker "BEEM"}
   {:ticker "BELFA"}
   {:ticker "BELFB"}
   {:ticker "BFC"}
   {:ticker "BFIN"}
   {:ticker "BFRA"}
   {:ticker "BFST"}
   {:ticker "BGCP"}
   {:ticker "BGFV"}
   {:ticker "BGNE"}
   {:ticker "BHAT"}
   {:ticker "BHF"}
   {:ticker "BHTG"}
   {:ticker "BIDU"}
   {:ticker "BIGC"}
   {:ticker "BIIB"}
   {:ticker "BILI"}
   {:ticker "BIMI"}
   {:ticker "BIOC"}
   {:ticker "BIOL"}
   {:ticker "BIVI"}
   {:ticker "BJRI"}
   {:ticker "BKEP"}
   {:ticker "BKNG"}
   {:ticker "BKSC"}
   {:ticker "BKYI"}
   {:ticker "BL"}
   {:ticker "BLBD"}
   {:ticker "BLCM"}
   {:ticker "BLCT"}
   {:ticker "BLDP"}
   {:ticker "BLDR"}
   {:ticker "BLFS"}
   {:ticker "BLI"}
   {:ticker "BLIN"}
   {:ticker "BLKB"}
   {:ticker "BLMN"}
   {:ticker "BLNK"}
   {:ticker "BLPH"}
   {:ticker "BLRX"}
   {:ticker "BLSA"}
   {:ticker "BLU"}
   {:ticker "BLUE"}
   {:ticker "BMCH"}
   {:ticker "BMRA"}
   {:ticker "BMRC"}
   {:ticker "BMRN"}
   {:ticker "BMTC"}
   {:ticker "BNFT"}
   {:ticker "BNGO"}
   {:ticker "BNR"}
   {:ticker "BNSO"}
   {:ticker "BNTC"}
   {:ticker "BNTX"}
   {:ticker "BOCH"}
   {:ticker "BOKF"}
   {:ticker "BOMN"}
   {:ticker "BOOM"}
   {:ticker "BOSC"}
   {:ticker "BOTJ"}
   {:ticker "BOWX"}
   {:ticker "BOXL"}
   {:ticker "BPFH"}
   {:ticker "BPMC"}
   {:ticker "BPOP"}
   {:ticker "BPRN"}
   {:ticker "BPTH"}
   {:ticker "BPY"}
   {:ticker "BPYU"}
   {:ticker "BRID"}
   {:ticker "BRKL"}
   {:ticker "BRKR"}
   {:ticker "BRKS"}
   {:ticker "BRLI"}
   {:ticker "BROG"}
   {:ticker "BRP"}
   {:ticker "BRPA"}
   {:ticker "BRQS"}
   {:ticker "BRY"}
   {:ticker "BSBK"}
   {:ticker "BSET"}
   {:ticker "BSGM"}
   {:ticker "BSQR"}
   {:ticker "BSRR"}
   {:ticker "BSVN"}
   {:ticker "BSY"}
   {:ticker "BTAI"}
   {:ticker "BTAQ"}
   {:ticker "BTBT"}
   {:ticker "BTWN"}
   {:ticker "BUSE"}
   {:ticker "BVXV"}
   {:ticker "BWAY"}
   {:ticker "BWB"}
   {:ticker "BWEN"}
   {:ticker "BWFG"}
   {:ticker "BWMX"}
   {:ticker "BXRX"}
   {:ticker "BYFC"}
   {:ticker "BYND"}
   {:ticker "BYSI"}
   {:ticker "BZUN"}
   {:ticker "CAAS"}
   {:ticker "CABA"}
   {:ticker "CAC"}
   {:ticker "CACC"}
   {:ticker "CAKE"}
   {:ticker "CALA"}
   {:ticker "CALB"}
   {:ticker "CALM"}
   {:ticker "CALT"}
   {:ticker "CAMP"}
   {:ticker "CAMT"}
   {:ticker "CAN"}
   {:ticker "CAPA"}
   {:ticker "CAPR"}
   {:ticker "CAR"}
   {:ticker "CARA"}
   {:ticker "CARE"}
   {:ticker "CARG"}
   {:ticker "CARV"}
   {:ticker "CASA"}
   {:ticker "CASH"}
   {:ticker "CASI"}
   {:ticker "CASS"}
   {:ticker "CASY"}
   {:ticker "CATB"}
   {:ticker "CATC"}
   {:ticker "CATM"}
   {:ticker "CATY"}
   {:ticker "CBAN"}
   {:ticker "CBAT"}
   {:ticker "CBAY"}
   {:ticker "CBFV"}
   {:ticker "CBIO"}
   {:ticker "CBLI"}
   {:ticker "CBMB"}
   {:ticker "CBMG"}
   {:ticker "CBNK"}
   {:ticker "CBPO"}
   {:ticker "CBRL"}
   {:ticker "CBSH"}
   {:ticker "CBTX"}
   {:ticker "CCAP"}
   {:ticker "CCB"}
   {:ticker "CCBG"}
   {:ticker "CCCC"}
   {:ticker "CCLP"}
   {:ticker "CCMP"}
   {:ticker "CCNC"}
   {:ticker "CCNE"}
   {:ticker "CCOI"}
   {:ticker "CCRC"}
   {:ticker "CCRN"}
   {:ticker "CCXI"}
   {:ticker "CD"}
   {:ticker "CDAK"}
   {:ticker "CDEV"}
   {:ticker "CDK"}
   {:ticker "CDLX"}
   {:ticker "CDMO"}
   {:ticker "CDNA"}
   {:ticker "CDNS"}
   {:ticker "CDTX"}
   {:ticker "CDW"}
   {:ticker "CDXC"}
   {:ticker "CDXS"}
   {:ticker "CDZI"}
   {:ticker "CECE"}
   {:ticker "CELC"}
   {:ticker "CELH"}
   {:ticker "CEMI"}
   {:ticker "CENT"}
   {:ticker "CENTA"}
   {:ticker "CENX"}
   {:ticker "CERC"}
   {:ticker "CERE"}
   {:ticker "CERN"}
   {:ticker "CERS"}
   {:ticker "CERT"}
   {:ticker "CETX"}
   {:ticker "CEVA"}
   {:ticker "CFB"}
   {:ticker "CFBI"}
   {:ticker "CFBK"}
   {:ticker "CFFI"}
   {:ticker "CFFN"}
   {:ticker "CFII"}
   {:ticker "CFMS"}
   {:ticker "CFRX"}
   {:ticker "CG"}
   {:ticker "CGC"}
   {:ticker "CGEN"}
   {:ticker "CGIX"}
   {:ticker "CGNX"}
   {:ticker "CGRO"}
   {:ticker "CHCI"}
   {:ticker "CHCO"}
   {:ticker "CHDN"}
   {:ticker "CHEF"}
   {:ticker "CHEK"}
   {:ticker "CHFS"}
   {:ticker "CHKP"}
   {:ticker "CHMA"}
   {:ticker "CHMG"}
   {:ticker "CHNG"}
   {:ticker "CHNR"}
   {:ticker "CHPM"}
   {:ticker "CHRS"}
   {:ticker "CHRW"}
   {:ticker "CHTR"}
   {:ticker "CHUY"}
   {:ticker "CIDM"}
   {:ticker "CIGI"}
   {:ticker "CIH"}
   {:ticker "CIIC"}
   {:ticker "CINF"}
   {:ticker "CIVB"}
   {:ticker "CIZN"}
   {:ticker "CJJD"}
   {:ticker "CKPT"}
   {:ticker "CLAR"}
   {:ticker "CLBK"}
   {:ticker "CLBS"}
   {:ticker "CLCT"}
   {:ticker "CLDB"}
   {:ticker "CLDX"}
   {:ticker "CLEU"}
   {:ticker "CLFD"}
   {:ticker "CLGN"}
   {:ticker "CLIR"}
   {:ticker "CLLS"}
   {:ticker "CLMT"}
   {:ticker "CLNE"}
   {:ticker "CLPS"}
   {:ticker "CLPT"}
   {:ticker "CLRB"}
   {:ticker "CLRO"}
   {:ticker "CLSD"}
   {:ticker "CLSK"}
   {:ticker "CLSN"}
   {:ticker "CLVS"}
   {:ticker "CLWT"}
   {:ticker "CLXT"}
   {:ticker "CMBM"}
   {:ticker "CMCO"}
   {:ticker "CMCSA"}
   {:ticker "CMCT"}
   {:ticker "CME"}
   {:ticker "CMLF"}
   {:ticker "CMLS"}
   {:ticker "CMPI"}
   {:ticker "CMPR"}
   {:ticker "CMPS"}
   {:ticker "CMRX"}
   {:ticker "CMTL"}
   {:ticker "CNBKA"}
   {:ticker "CNCE"}
   {:ticker "CNDT"}
   {:ticker "CNET"}
   {:ticker "CNFR"}
   {:ticker "CNNB"}
   {:ticker "CNOB"}
   {:ticker "CNSL"}
   {:ticker "CNSP"}
   {:ticker "CNST"}
   {:ticker "CNTG"}
   {:ticker "CNTY"}
   {:ticker "CNXC"}
   {:ticker "CNXN"}
   {:ticker "COCP"}
   {:ticker "CODA"}
   {:ticker "CODX"}
   {:ticker "COFS"}
   {:ticker "COGT"}
   {:ticker "COHR"}
   {:ticker "COHU"}
   {:ticker "COKE"}
   {:ticker "COLB"}
   {:ticker "COLL"}
   {:ticker "COLM"}
   {:ticker "COMM"}
   {:ticker "CONE"}
   {:ticker "CONN"}
   {:ticker "COOP"}
   {:ticker "CORE"}
   {:ticker "CORT"}
   {:ticker "COST"}
   {:ticker "COUP"}
   {:ticker "COWN"}
   {:ticker "CPAH"}
   {:ticker "CPHC"}
   {:ticker "CPIX"}
   {:ticker "CPLP"}
   {:ticker "CPRT"}
   {:ticker "CPRX"}
   {:ticker "CPSH"}
   {:ticker "CPSI"}
   {:ticker "CPSS"}
   {:ticker "CPST"}
   {:ticker "CPTA"}
   {:ticker "CRAI"}
   {:ticker "CRBP"}
   {:ticker "CRDF"}
   {:ticker "CREE"}
   {:ticker "CREG"}
   {:ticker "CRESY"}
   {:ticker "CREX"}
   {:ticker "CRIS"}
   {:ticker "CRMT"}
   {:ticker "CRNC"}
   {:ticker "CRNT"}
   {:ticker "CRNX"}
   {:ticker "CRON"}
   {:ticker "CROX"}
   {:ticker "CRSA"}
   {:ticker "CRSP"}
   {:ticker "CRSR"}
   {:ticker "CRTD"}
   {:ticker "CRTO"}
   {:ticker "CRTX"}
   {:ticker "CRUS"}
   {:ticker "CRVL"}
   {:ticker "CRVS"}
   {:ticker "CRWD"}
   {:ticker "CRWS"}
   {:ticker "CSBR"}
   {:ticker "CSCO"}
   {:ticker "CSCW"}
   {:ticker "CSGP"}
   {:ticker "CSGS"}
   {:ticker "CSII"}
   {:ticker "CSIQ"}
   {:ticker "CSOD"}
   {:ticker "CSPI"}
   {:ticker "CSSE"}
   {:ticker "CSTE"}
   {:ticker "CSTL"}
   {:ticker "CSTR"}
   {:ticker "CSWC"}
   {:ticker "CSWI"}
   {:ticker "CSX"}
   {:ticker "CTAS"}
   {:ticker "CTBI"}
   {:ticker "CTG"}
   {:ticker "CTHR"}
   {:ticker "CTIB"}
   {:ticker "CTIC"}
   {:ticker "CTMX"}
   {:ticker "CTRE"}
   {:ticker "CTRM"}
   {:ticker "CTRN"}
   {:ticker "CTSH"}
   {:ticker "CTSO"}
   {:ticker "CTXR"}
   {:ticker "CTXS"}
   {:ticker "CUE"}
   {:ticker "CURI"}
   {:ticker "CUTR"}
   {:ticker "CVAC"}
   {:ticker "CVBF"}
   {:ticker "CVCO"}
   {:ticker "CVCY"}
   {:ticker "CVET"}
   {:ticker "CVGI"}
   {:ticker "CVGW"}
   {:ticker "CVLB"}
   {:ticker "CVLG"}
   {:ticker "CVLT"}
   {:ticker "CVLY"}
   {:ticker "CVV"}
   {:ticker "CWBC"}
   {:ticker "CWBR"}
   {:ticker "CWCO"}
   {:ticker "CWST"}
   {:ticker "CXDC"}
   {:ticker "CXDO"}
   {:ticker "CYAD"}
   {:ticker "CYAN"}
   {:ticker "CYBE"}
   {:ticker "CYBR"}
   {:ticker "CYCC"}
   {:ticker "CYCN"}
   {:ticker "CYRN"}
   {:ticker "CYRX"}
   {:ticker "CYTH"}
   {:ticker "CYTK"}
   {:ticker "CZNC"}
   {:ticker "CZR"}
   {:ticker "CZWI"}
   {:ticker "DADA"}
   {:ticker "DAIO"}
   {:ticker "DAKT"}
   {:ticker "DARE"}
   {:ticker "DBDR"}
   {:ticker "DBVT"}
   {:ticker "DBX"}
   {:ticker "DCBO"}
   {:ticker "DCOM"}
   {:ticker "DCPH"}
   {:ticker "DCRB"}
   {:ticker "DCT"}
   {:ticker "DCTH"}
   {:ticker "DDOG"}
   {:ticker "DENN"}
   {:ticker "DFFN"}
   {:ticker "DFHT"}
   {:ticker "DFPH"}
   {:ticker "DGICA"}
   {:ticker "DGICB"}
   {:ticker "DGII"}
   {:ticker "DGLY"}
   {:ticker "DGNS"}
   {:ticker "DHC"}
   {:ticker "DHIL"}
   {:ticker "DIOD"}
   {:ticker "DISCA"}
   {:ticker "DISCB"}
   {:ticker "DISCK"}
   {:ticker "DISH"}
   {:ticker "DJCO"}
   {:ticker "DKNG"}
   {:ticker "DLHC"}
   {:ticker "DLPN"}
   {:ticker "DLTH"}
   {:ticker "DLTR"}
   {:ticker "DMAC"}
   {:ticker "DMLP"}
   {:ticker "DMRC"}
   {:ticker "DMTK"}
   {:ticker "DNLI"}
   {:ticker "DOCU"}
   {:ticker "DOGZ"}
   {:ticker "DOMO"}
   {:ticker "DOOO"}
   {:ticker "DORM"}
   {:ticker "DOX"}
   {:ticker "DOYU"}
   {:ticker "DRAD"}
   {:ticker "DRIO"}
   {:ticker "DRNA"}
   {:ticker "DRRX"}
   {:ticker "DRTT"}
   {:ticker "DSAC"}
   {:ticker "DSGX"}
   {:ticker "DSKE"}
   {:ticker "DSPG"}
   {:ticker "DSWL"}
   {:ticker "DTEA"}
   {:ticker "DTIL"}
   {:ticker "DTSS"}
   {:ticker "DUO"}
   {:ticker "DUOT"}
   {:ticker "DVAX"}
   {:ticker "DWSN"}
   {:ticker "DXCM"}
   {:ticker "DXLG"}
   {:ticker "DXPE"}
   {:ticker "DXYN"}
   {:ticker "DYAI"}
   {:ticker "DYN"}
   {:ticker "DYNT"}
   {:ticker "DZSI"}
   {:ticker "EA"}
   {:ticker "EAR"}
   {:ticker "EARS"}
   {:ticker "EAST"}
   {:ticker "EBAY"}
   {:ticker "EBC"}
   {:ticker "EBIX"}
   {:ticker "EBMT"}
   {:ticker "EBON"}
   {:ticker "EBSB"}
   {:ticker "EBTC"}
   {:ticker "ECHO"}
   {:ticker "ECOL"}
   {:ticker "ECOR"}
   {:ticker "ECPG"}
   {:ticker "EDAP"}
   {:ticker "EDIT"}
   {:ticker "EDRY"}
   {:ticker "EDSA"}
   {:ticker "EDTK"}
   {:ticker "EDUC"}
   {:ticker "EEFT"}
   {:ticker "EFOI"}
   {:ticker "EFSC"}
   {:ticker "EGAN"}
   {:ticker "EGBN"}
   {:ticker "EGLE"}
   {:ticker "EGOV"}
   {:ticker "EGRX"}
   {:ticker "EH"}
   {:ticker "EHTH"}
   {:ticker "EIDX"}
   {:ticker "EIGI"}
   {:ticker "EIGR"}
   {:ticker "EKSO"}
   {:ticker "ELOX"}
   {:ticker "ELSE"}
   {:ticker "ELTK"}
   {:ticker "ELYS"}
   {:ticker "EMCF"}
   {:ticker "EMKR"}
   {:ticker "EML"}
   {:ticker "ENDP"}
   {:ticker "ENG"}
   {:ticker "ENLV"}
   {:ticker "ENOB"}
   {:ticker "ENPH"}
   {:ticker "ENSG"}
   {:ticker "ENTA"}
   {:ticker "ENTG"}
   {:ticker "ENTX"}
   {:ticker "EOLS"}
   {:ticker "EOSE"}
   {:ticker "EPAY"}
   {:ticker "EPIX"}
   {:ticker "EPSN"}
   {:ticker "EPZM"}
   {:ticker "EQ"}
   {:ticker "EQBK"}
   {:ticker "EQIX"}
   {:ticker "EQOS"}
   {:ticker "ERES"}
   {:ticker "ERIC"}
   {:ticker "ERIE"}
   {:ticker "ERII"}
   {:ticker "ERYP"}
   {:ticker "ESBK"}
   {:ticker "ESCA"}
   {:ticker "ESEA"}
   {:ticker "ESGR"}
   {:ticker "ESLT"}
   {:ticker "ESPR"}
   {:ticker "ESQ"}
   {:ticker "ESSA"}
   {:ticker "ESSC"}
   {:ticker "ESTA"}
   {:ticker "ESXB"}
   {:ticker "ETAC"}
   {:ticker "ETNB"}
   {:ticker "ETON"}
   {:ticker "ETSY"}
   {:ticker "ETTX"}
   {:ticker "EVBG"}
   {:ticker "EVER"}
   {:ticker "EVFM"}
   {:ticker "EVGN"}
   {:ticker "EVK"}
   {:ticker "EVLO"}
   {:ticker "EVOK"}
   {:ticker "EVOL"}
   {:ticker "EVOP"}
   {:ticker "EWBC"}
   {:ticker "EXAS"}
   {:ticker "EXC"}
   {:ticker "EXEL"}
   {:ticker "EXFO"}
   {:ticker "EXLS"}
   {:ticker "EXPC"}
   {:ticker "EXPD"}
   {:ticker "EXPE"}
   {:ticker "EXPI"}
   {:ticker "EXPO"}
   {:ticker "EXTR"}
   {:ticker "EYE"}
   {:ticker "EYEG"}
   {:ticker "EYEN"}
   {:ticker "EYES"}
   {:ticker "EYPT"}
   {:ticker "EZPW"}
   {:ticker "FAMI"}
   {:ticker "FANG"}
   {:ticker "FANH"}
   {:ticker "FARM"}
   {:ticker "FARO"}
   {:ticker "FAST"}
   {:ticker "FAT"}
   {:ticker "FATE"}
   {:ticker "FB"}
   {:ticker "FBIO"}
   {:ticker "FBIZ"}
   {:ticker "FBMS"}
   {:ticker "FBNC"}
   {:ticker "FBRX"}
   {:ticker "FBSS"}
   {:ticker "FCAC"}
   {:ticker "FCAP"}
   {:ticker "FCBC"}
   {:ticker "FCBP"}
   {:ticker "FCCO"}
   {:ticker "FCCY"}
   {:ticker "FCEL"}
   {:ticker "FCFS"}
   {:ticker "FCNCA"}
   {:ticker "FDBC"}
   {:ticker "FDMT"}
   {:ticker "FEIM"}
   {:ticker "FELE"}
   {:ticker "FENC"}
   {:ticker "FEYE"}
   {:ticker "FFBC"}
   {:ticker "FFBW"}
   {:ticker "FFHL"}
   {:ticker "FFIC"}
   {:ticker "FFIN"}
   {:ticker "FFIV"}
   {:ticker "FFNW"}
   {:ticker "FFWM"}
   {:ticker "FGBI"}
   {:ticker "FGEN"}
   {:ticker "FHB"}
   {:ticker "FHTX"}
   {:ticker "FIBK"}
   {:ticker "FIII"}
   {:ticker "FISI"}
   {:ticker "FISV"}
   {:ticker "FITB"}
   {:ticker "FIVE"}
   {:ticker "FIVN"}
   {:ticker "FIXX"}
   {:ticker "FIZZ"}
   {:ticker "FLDM"}
   {:ticker "FLEX"}
   {:ticker "FLGT"}
   {:ticker "FLIC"}
   {:ticker "FLIR"}
   {:ticker "FLL"}
   {:ticker "FLMN"}
   {:ticker "FLNT"}
   {:ticker "FLUX"}
   {:ticker "FLWS"}
   {:ticker "FLXN"}
   {:ticker "FLXS"}
   {:ticker "FMAO"}
   {:ticker "FMBH"}
   {:ticker "FMBI"}
   {:ticker "FMNB"}
   {:ticker "FMTX"}
   {:ticker "FNCB"}
   {:ticker "FNHC"}
   {:ticker "FNKO"}
   {:ticker "FNLC"}
   {:ticker "FNWB"}
   {:ticker "FOCS"}
   {:ticker "FOLD"}
   {:ticker "FONR"}
   {:ticker "FORD"}
   {:ticker "FORM"}
   {:ticker "FORR"}
   {:ticker "FORTY"}
   {:ticker "FOSL"}
   {:ticker "FOX"}
   {:ticker "FOXA"}
   {:ticker "FOXF"}
   {:ticker "FPAY"}
   {:ticker "FPRX"}
   {:ticker "FRAF"}
   {:ticker "FRBA"}
   {:ticker "FRBK"}
   {:ticker "FREE"}
   {:ticker "FREQ"}
   {:ticker "FRG"}
   {:ticker "FRGI"}
   {:ticker "FRHC"}
   {:ticker "FRLN"}
   {:ticker "FRME"}
   {:ticker "FROG"}
   {:ticker "FRPH"}
   {:ticker "FRPT"}
   {:ticker "FRSX"}
   {:ticker "FRTA"}
   {:ticker "FSBW"}
   {:ticker "FSDC"}
   {:ticker "FSEA"}
   {:ticker "FSFG"}
   {:ticker "FSLR"}
   {:ticker "FSRV"}
   {:ticker "FSTR"}
   {:ticker "FSTX"}
   {:ticker "FSV"}
   {:ticker "FTDR"}
   {:ticker "FTEK"}
   {:ticker "FTFT"}
   {:ticker "FTHM"}
   {:ticker "FTIV"}
   {:ticker "FTNT"}
   {:ticker "FTOC"}
   {:ticker "FULC"}
   {:ticker "FULT"}
   {:ticker "FUNC"}
   {:ticker "FUSB"}
   {:ticker "FUSN"}
   {:ticker "FUTU"}
   {:ticker "FUV"}
   {:ticker "FVAM"}
   {:ticker "FVCB"}
   {:ticker "FVE"}
   {:ticker "FWONA"}
   {:ticker "FWONK"}
   {:ticker "FWP"}
   {:ticker "FWRD"}
   {:ticker "FXNC"}
   {:ticker "GABC"}
   {:ticker "GAIA"}
   {:ticker "GALT"}
   {:ticker "GAN"}
   {:ticker "GASS"}
   {:ticker "GBCI"}
   {:ticker "GBIO"}
   {:ticker "GBLI"}
   {:ticker "GBT"}
   {:ticker "GCBC"}
   {:ticker "GCMG"}
   {:ticker "GDEN"}
   {:ticker "GDRX"}
   {:ticker "GDS"}
   {:ticker "GDYN"}
   {:ticker "GEC"}
   {:ticker "GENC"}
   {:ticker "GENE"}
   {:ticker "GEOS"}
   {:ticker "GERN"}
   {:ticker "GEVO"}
   {:ticker "GFED"}
   {:ticker "GFN"}
   {:ticker "GGAL"}
   {:ticker "GH"}
   {:ticker "GHIV"}
   {:ticker "GHSI"}
   {:ticker "GIFI"}
   {:ticker "GIGM"}
   {:ticker "GIII"}
   {:ticker "GILD"}
   {:ticker "GILT"}
   {:ticker "GLBS"}
   {:ticker "GLBZ"}
   {:ticker "GLDD"}
   {:ticker "GLG"}
   {:ticker "GLIBA"}
   {:ticker "GLMD"}
   {:ticker "GLNG"}
   {:ticker "GLPG"}
   {:ticker "GLPI"}
   {:ticker "GLRE"}
   {:ticker "GLSI"}
   {:ticker "GLTO"}
   {:ticker "GLUU"}
   {:ticker "GLYC"}
   {:ticker "GMAB"}
   {:ticker "GMBL"}
   {:ticker "GMDA"}
   {:ticker "GMLP"}
   {:ticker "GNCA"}
   {:ticker "GNFT"}
   {:ticker "GNLN"}
   {:ticker "GNMK"}
   {:ticker "GNPX"}
   {:ticker "GNRS"}
   {:ticker "GNSS"}
   {:ticker "GNTX"}
   {:ticker "GNTY"}
   {:ticker "GNUS"}
   {:ticker "GO"}
   {:ticker "GOCO"}
   {:ticker "GOGL"}
   {:ticker "GOGO"}
   {:ticker "GOOD"}
   {:ticker "GOOG"}
   {:ticker "GOOGL"}
   {:ticker "GOSS"}
   {:ticker "GOVX"}
   {:ticker "GP"}
   {:ticker "GPP"}
   {:ticker "GPRE"}
   {:ticker "GPRO"}
   {:ticker "GRAY"}
   {:ticker "GRBK"}
   {:ticker "GRCY"}
   {:ticker "GRFS"}
   {:ticker "GRIF"}
   {:ticker "GRIL"}
   {:ticker "GRIN"}
   {:ticker "GRMN"}
   {:ticker "GRNQ"}
   {:ticker "GRNV"}
   {:ticker "GROW"}
   {:ticker "GRPN"}
   {:ticker "GRSV"}
   {:ticker "GRTS"}
   {:ticker "GRTX"}
   {:ticker "GRVY"}
   {:ticker "GRWG"}
   {:ticker "GSBC"}
   {:ticker "GSHD"}
   {:ticker "GSIT"}
   {:ticker "GSKY"}
   {:ticker "GSM"}
   {:ticker "GSMG"}
   {:ticker "GSUM"}
   {:ticker "GT"}
   {:ticker "GTEC"}
   {:ticker "GTH"}
   {:ticker "GTHX"}
   {:ticker "GTIM"}
   {:ticker "GTLS"}
   {:ticker "GTYH"}
   {:ticker "GURE"}
   {:ticker "GVP"}
   {:ticker "GWAC"}
   {:ticker "GWGH"}
   {:ticker "GWPH"}
   {:ticker "GWRS"}
   {:ticker "GXGX"}
   {:ticker "GYRO"}
   {:ticker "HA"}
   {:ticker "HAFC"}
   {:ticker "HAIN"}
   {:ticker "HALL"}
   {:ticker "HALO"}
   {:ticker "HAPP"}
   {:ticker "HARP"}
   {:ticker "HAS"}
   {:ticker "HAYN"}
   {:ticker "HBAN"}
   {:ticker "HBCP"}
   {:ticker "HBIO"}
   {:ticker "HBMD"}
   {:ticker "HBNC"}
   {:ticker "HBP"}
   {:ticker "HBT"}
   {:ticker "HCAC"}
   {:ticker "HCAP"}
   {:ticker "HCAT"}
   {:ticker "HCCI"}
   {:ticker "HCDI"}
   {:ticker "HCKT"}
   {:ticker "HCM"}
   {:ticker "HCSG"}
   {:ticker "HDS"}
   {:ticker "HDSN"}
   {:ticker "HEAR"}
   {:ticker "HEC"}
   {:ticker "HEES"}
   {:ticker "HELE"}
   {:ticker "HEPA"}
   {:ticker "HFBL"}
   {:ticker "HFEN"}
   {:ticker "HFFG"}
   {:ticker "HFWA"}
   {:ticker "HGBL"}
   {:ticker "HGEN"}
   {:ticker "HGSH"}
   {:ticker "HHR"}
   {:ticker "HIBB"}
   {:ticker "HIFS"}
   {:ticker "HIHO"}
   {:ticker "HIMX"}
   {:ticker "HJLI"}
   {:ticker "HLG"}
   {:ticker "HLIO"}
   {:ticker "HLIT"}
   {:ticker "HLNE"}
   {:ticker "HLXA"}
   {:ticker "HMHC"}
   {:ticker "HMNF"}
   {:ticker "HMST"}
   {:ticker "HMSY"}
   {:ticker "HMTV"}
   {:ticker "HNNA"}
   {:ticker "HNRG"}
   {:ticker "HOFT"}
   {:ticker "HOFV"}
   {:ticker "HOL"}
   {:ticker "HOLI"}
   {:ticker "HOLX"}
   {:ticker "HOMB"}
   {:ticker "HONE"}
   {:ticker "HOOK"}
   {:ticker "HOPE"}
   {:ticker "HOTH"}
   {:ticker "HPK"}
   {:ticker "HQI"}
   {:ticker "HQY"}
   {:ticker "HRMY"}
   {:ticker "HROW"}
   {:ticker "HRTX"}
   {:ticker "HRZN"}
   {:ticker "HSAQ"}
   {:ticker "HSDT"}
   {:ticker "HSIC"}
   {:ticker "HSII"}
   {:ticker "HSKA"}
   {:ticker "HSON"}
   {:ticker "HST"}
   {:ticker "HSTM"}
   {:ticker "HSTO"}
   {:ticker "HTBI"}
   {:ticker "HTBK"}
   {:ticker "HTBX"}
   {:ticker "HTGM"}
   {:ticker "HTHT"}
   {:ticker "HTLD"}
   {:ticker "HTLF"}
   {:ticker "HTOO"}
   {:ticker "HUBG"}
   {:ticker "HUGE"}
   {:ticker "HUIZ"}
   {:ticker "HURC"}
   {:ticker "HURN"}
   {:ticker "HUSN"}
   {:ticker "HVBC"}
   {:ticker "HWBK"}
   {:ticker "HWC"}
   {:ticker "HWCC"}
   {:ticker "HWKN"}
   {:ticker "HX"}
   {:ticker "HYAC"}
   {:ticker "HYFM"}
   {:ticker "HYMC"}
   {:ticker "HYRE"}
   {:ticker "HZNP"}
   {:ticker "IAC"}
   {:ticker "IART"}
   {:ticker "IBCP"}
   {:ticker "IBEX"}
   {:ticker "IBKR"}
   {:ticker "IBOC"}
   {:ticker "IBTX"}
   {:ticker "ICAD"}
   {:ticker "ICBK"}
   {:ticker "ICCC"}
   {:ticker "ICCH"}
   {:ticker "ICFI"}
   {:ticker "ICHR"}
   {:ticker "ICLK"}
   {:ticker "ICLR"}
   {:ticker "ICMB"}
   {:ticker "ICON"}
   {:ticker "ICPT"}
   {:ticker "ICUI"}
   {:ticker "IDCC"}
   {:ticker "IDEX"}
   {:ticker "IDN"}
   {:ticker "IDRA"}
   {:ticker "IDXG"}
   {:ticker "IDXX"}
   {:ticker "IDYA"}
   {:ticker "IEA"}
   {:ticker "IEC"}
   {:ticker "IEP"}
   {:ticker "IESC"}
   {:ticker "IFMK"}
   {:ticker "IFRX"}
   {:ticker "IGAC"}
   {:ticker "IGIC"}
   {:ticker "IGMS"}
   {:ticker "IHRT"}
   {:ticker "III"}
   {:ticker "IIIN"}
   {:ticker "IIIV"}
   {:ticker "IIN"}
   {:ticker "IIVI"}
   {:ticker "IKNX"}
   {:ticker "ILMN"}
   {:ticker "ILPT"}
   {:ticker "IMAB"}
   {:ticker "IMAC"}
   {:ticker "IMBI"}
   {:ticker "IMGN"}
   {:ticker "IMKTA"}
   {:ticker "IMMP"}
   {:ticker "IMMR"}
   {:ticker "IMNM"}
   {:ticker "IMOS"}
   {:ticker "IMRA"}
   {:ticker "IMRN"}
   {:ticker "IMTE"}
   {:ticker "IMTX"}
   {:ticker "IMUX"}
   {:ticker "IMV"}
   {:ticker "IMVT"}
   {:ticker "IMXI"}
   {:ticker "INAQ"}
   {:ticker "INBK"}
   {:ticker "INBX"}
   {:ticker "INCY"}
   {:ticker "INDB"}
   {:ticker "INFI"}
   {:ticker "INFN"}
   {:ticker "INGN"}
   {:ticker "INM"}
   {:ticker "INMB"}
   {:ticker "INMD"}
   {:ticker "INO"}
   {:ticker "INOD"}
   {:ticker "INOV"}
   {:ticker "INPX"}
   {:ticker "INSE"}
   {:ticker "INSG"}
   {:ticker "INSM"}
   {:ticker "INTC"}
   {:ticker "INTG"}
   {:ticker "INTU"}
   {:ticker "INTZ"}
   {:ticker "INVA"}
   {:ticker "INVE"}
   {:ticker "INVO"}
   {:ticker "INZY"}
   {:ticker "IONS"}
   {:ticker "IOSP"}
   {:ticker "IOVA"}
   {:ticker "IPAR"}
   {:ticker "IPDN"}
   {:ticker "IPGP"}
   {:ticker "IPHA"}
   {:ticker "IPHI"}
   {:ticker "IPWR"}
   {:ticker "IQ"}
   {:ticker "IRBT"}
   {:ticker "IRCP"}
   {:ticker "IRDM"}
   {:ticker "IRIX"}
   {:ticker "IRMD"}
   {:ticker "IROQ"}
   {:ticker "IRTC"}
   {:ticker "IRWD"}
   {:ticker "ISBC"}
   {:ticker "ISEE"}
   {:ticker "ISIG"}
   {:ticker "ISNS"}
   {:ticker "ISRG"}
   {:ticker "ISSC"}
   {:ticker "ISTR"}
   {:ticker "ITAC"}
   {:ticker "ITCI"}
   {:ticker "ITI"}
   {:ticker "ITIC"}
   {:ticker "ITMR"}
   {:ticker "ITOS"}
   {:ticker "ITRI"}
   {:ticker "ITRM"}
   {:ticker "ITRN"}
   {:ticker "IVA"}
   {:ticker "IVAC"}
   {:ticker "IZEA"}
   {:ticker "JACK"}
   {:ticker "JAGX"}
   {:ticker "JAKK"}
   {:ticker "JAMF"}
   {:ticker "JAN"}
   {:ticker "JAZZ"}
   {:ticker "JBHT"}
   {:ticker "JBLU"}
   {:ticker "JBSS"}
   {:ticker "JCOM"}
   {:ticker "JCS"}
   {:ticker "JCTCF"}
   {:ticker "JD"}
   {:ticker "JFIN"}
   {:ticker "JFU"}
   {:ticker "JG"}
   {:ticker "JJSF"}
   {:ticker "JKHY"}
   {:ticker "JNCE"}
   {:ticker "JOBS"}
   {:ticker "JOUT"}
   {:ticker "JRJC"}
   {:ticker "JRSH"}
   {:ticker "JRVR"}
   {:ticker "JUPW"}
   {:ticker "JVA"}
   {:ticker "JYAC"}
   {:ticker "JYNT"}
   {:ticker "KALA"}
   {:ticker "KALU"}
   {:ticker "KALV"}
   {:ticker "KBAL"}
   {:ticker "KBNT"}
   {:ticker "KBSF"}
   {:ticker "KC"}
   {:ticker "KDMN"}
   {:ticker "KDNY"}
   {:ticker "KDP"}
   {:ticker "KE"}
   {:ticker "KELYA"}
   {:ticker "KELYB"}
   {:ticker "KEQU"}
   {:ticker "KERN"}
   {:ticker "KFFB"}
   {:ticker "KFRC"}
   {:ticker "KHC"}
   {:ticker "KIDS"}
   {:ticker "KIN"}
   {:ticker "KINS"}
   {:ticker "KIRK"}
   {:ticker "KLAC"}
   {:ticker "KLDO"}
   {:ticker "KLIC"}
   {:ticker "KLXE"}
   {:ticker "KMDA"}
   {:ticker "KNDI"}
   {:ticker "KNSA"}
   {:ticker "KNSL"}
   {:ticker "KNTE"}
   {:ticker "KOD"}
   {:ticker "KOPN"}
   {:ticker "KOR"}
   {:ticker "KOSS"}
   {:ticker "KPTI"}
   {:ticker "KRBP"}
   {:ticker "KRKR"}
   {:ticker "KRMD"}
   {:ticker "KRNT"}
   {:ticker "KRNY"}
   {:ticker "KRON"}
   {:ticker "KROS"}
   {:ticker "KRTX"}
   {:ticker "KRUS"}
   {:ticker "KRYS"}
   {:ticker "KSMT"}
   {:ticker "KSPN"}
   {:ticker "KTCC"}
   {:ticker "KTOS"}
   {:ticker "KTOV"}
   {:ticker "KTRA"}
   {:ticker "KURA"}
   {:ticker "KVHI"}
   {:ticker "KXIN"}
   {:ticker "KYMR"}
   {:ticker "KZIA"}
   {:ticker "KZR"}
   {:ticker "LACQ"}
   {:ticker "LAKE"}
   {:ticker "LAMR"}
   {:ticker "LANC"}
   {:ticker "LAND"}
   {:ticker "LARK"}
   {:ticker "LASR"}
   {:ticker "LATN"}
   {:ticker "LAUR"}
   {:ticker "LAWS"}
   {:ticker "LAZR"}
   {:ticker "LAZY"}
   {:ticker "LBAI"}
   {:ticker "LBC"}
   {:ticker "LBRDA"}
   {:ticker "LBRDK"}
   {:ticker "LBTYA"}
   {:ticker "LBTYB"}
   {:ticker "LBTYK"}
   {:ticker "LCA"}
   {:ticker "LCAP"}
   {:ticker "LCNB"}
   {:ticker "LCUT"}
   {:ticker "LCY"}
   {:ticker "LE"}
   {:ticker "LECO"}
   {:ticker "LEDS"}
   {:ticker "LEGH"}
   {:ticker "LEGN"}
   {:ticker "LESL"}
   {:ticker "LEVL"}
   {:ticker "LFAC"}
   {:ticker "LFUS"}
   {:ticker "LFVN"}
   {:ticker "LGHL"}
   {:ticker "LGIH"}
   {:ticker "LGND"}
   {:ticker "LHCG"}
   {:ticker "LI"}
   {:ticker "LIFE"}
   {:ticker "LILA"}
   {:ticker "LILAK"}
   {:ticker "LINC"}
   {:ticker "LIND"}
   {:ticker "LIQT"}
   {:ticker "LITE"}
   {:ticker "LIVE"}
   {:ticker "LIVK"}
   {:ticker "LIVN"}
   {:ticker "LIVX"}
   {:ticker "LIXT"}
   {:ticker "LIZI"}
   {:ticker "LJPC"}
   {:ticker "LKCO"}
   {:ticker "LKFN"}
   {:ticker "LKQ"}
   {:ticker "LLIT"}
   {:ticker "LLNW"}
   {:ticker "LMAT"}
   {:ticker "LMB"}
   {:ticker "LMFA"}
   {:ticker "LMNL"}
   {:ticker "LMNR"}
   {:ticker "LMNX"}
   {:ticker "LMPX"}
   {:ticker "LMRK"}
   {:ticker "LMST"}
   {:ticker "LNDC"}
   {:ticker "LNSR"}
   {:ticker "LNT"}
   {:ticker "LNTH"}
   {:ticker "LOAC"}
   {:ticker "LOAN"}
   {:ticker "LOB"}
   {:ticker "LOCO"}
   {:ticker "LOGC"}
   {:ticker "LOGI"}
   {:ticker "LOOP"}
   {:ticker "LOPE"}
   {:ticker "LORL"}
   {:ticker "LOVE"}
   {:ticker "LPCN"}
   {:ticker "LPLA"}
   {:ticker "LPRO"}
   {:ticker "LPSN"}
   {:ticker "LPTH"}
   {:ticker "LPTX"}
   {:ticker "LQDA"}
   {:ticker "LQDT"}
   {:ticker "LRCX"}
   {:ticker "LRMR"}
   {:ticker "LSAC"}
   {:ticker "LSAQ"}
   {:ticker "LSBK"}
   {:ticker "LSCC"}
   {:ticker "LSTR"}
   {:ticker "LSXMA"}
   {:ticker "LSXMB"}
   {:ticker "LSXMK"}
   {:ticker "LTBR"}
   {:ticker "LTRN"}
   {:ticker "LTRPA"}
   {:ticker "LTRPB"}
   {:ticker "LTRX"}
   {:ticker "LULU"}
   {:ticker "LUMO"}
   {:ticker "LUNA"}
   {:ticker "LUNG"}
   {:ticker "LWAY"}
   {:ticker "LX"}
   {:ticker "LXEH"}
   {:ticker "LXRX"}
   {:ticker "LYFT"}
   {:ticker "LYL"}
   {:ticker "LYRA"}
   {:ticker "LYTS"}
   {:ticker "MAAC"}
   {:ticker "MACK"}
   {:ticker "MACU"}
   {:ticker "MAGS"}
   {:ticker "MANH"}
   {:ticker "MANT"}
   {:ticker "MAR"}
   {:ticker "MARA"}
   {:ticker "MARK"}
   {:ticker "MARPS"}
   {:ticker "MASI"}
   {:ticker "MAT"}
   {:ticker "MATW"}
   {:ticker "MAXN"}
   {:ticker "MAYS"}
   {:ticker "MBCN"}
   {:ticker "MBII"}
   {:ticker "MBIN"}
   {:ticker "MBIO"}
   {:ticker "MBOT"}
   {:ticker "MBRX"}
   {:ticker "MBUU"}
   {:ticker "MBWM"}
   {:ticker "MCAC"}
   {:ticker "MCBC"}
   {:ticker "MCBS"}
   {:ticker "MCEP"}
   {:ticker "MCFE"}
   {:ticker "MCFT"}
   {:ticker "MCHP"}
   {:ticker "MCHX"}
   {:ticker "MCMJ"}
   {:ticker "MCRB"}
   {:ticker "MCRI"}
   {:ticker "MDB"}
   {:ticker "MDCA"}
   {:ticker "MDGL"}
   {:ticker "MDGS"}
   {:ticker "MDIA"}
   {:ticker "MDJH"}
   {:ticker "MDLZ"}
   {:ticker "MDNA"}
   {:ticker "MDRR"}
   {:ticker "MDRX"}
   {:ticker "MDVL"}
   {:ticker "MDWD"}
   {:ticker "MDXG"}
   {:ticker "MEDP"}
   {:ticker "MEDS"}
   {:ticker "MEIP"}
   {:ticker "MELI"}
   {:ticker "MEOH"}
   {:ticker "MERC"}
   {:ticker "MESA"}
   {:ticker "MESO"}
   {:ticker "METC"}
   {:ticker "METX"}
   {:ticker "MFH"}
   {:ticker "MFIN"}
   {:ticker "MFNC"}
   {:ticker "MGEE"}
   {:ticker "MGEN"}
   {:ticker "MGI"}
   {:ticker "MGIC"}
   {:ticker "MGLN"}
   {:ticker "MGNI"}
   {:ticker "MGNX"}
   {:ticker "MGPI"}
   {:ticker "MGRC"}
   {:ticker "MGTA"}
   {:ticker "MGTX"}
   {:ticker "MGYR"}
   {:ticker "MHLD"}
   {:ticker "MICT"}
   {:ticker "MIDD"}
   {:ticker "MIK"}
   {:ticker "MIME"}
   {:ticker "MIND"}
   {:ticker "MIRM"}
   {:ticker "MIST"}
   {:ticker "MITK"}
   {:ticker "MITO"}
   {:ticker "MKD"}
   {:ticker "MKGI"}
   {:ticker "MKSI"}
   {:ticker "MKTX"}
   {:ticker "MLAB"}
   {:ticker "MLAC"}
   {:ticker "MLCO"}
   {:ticker "MLHR"}
   {:ticker "MLND"}
   {:ticker "MLVF"}
   {:ticker "MMAC"}
   {:ticker "MMLP"}
   {:ticker "MMSI"}
   {:ticker "MMYT"}
   {:ticker "MNCL"}
   {:ticker "MNDO"}
   {:ticker "MNKD"}
   {:ticker "MNOV"}
   {:ticker "MNPR"}
   {:ticker "MNRO"}
   {:ticker "MNSB"}
   {:ticker "MNST"}
   {:ticker "MNTX"}
   {:ticker "MOFG"}
   {:ticker "MOGO"}
   {:ticker "MOHO"}
   {:ticker "MOMO"}
   {:ticker "MOR"}
   {:ticker "MORF"}
   {:ticker "MORN"}
   {:ticker "MOSY"}
   {:ticker "MOTN"}
   {:ticker "MOTS"}
   {:ticker "MOXC"}
   {:ticker "MPAA"}
   {:ticker "MPB"}
   {:ticker "MPWR"}
   {:ticker "MRAM"}
   {:ticker "MRBK"}
   {:ticker "MRCY"}
   {:ticker "MREO"}
   {:ticker "MRIN"}
   {:ticker "MRKR"}
   {:ticker "MRLN"}
   {:ticker "MRNA"}
   {:ticker "MRNS"}
   {:ticker "MRSN"}
   {:ticker "MRTN"}
   {:ticker "MRTX"}
   {:ticker "MRUS"}
   {:ticker "MRVI"}
   {:ticker "MRVL"}
   {:ticker "MSBI"}
   {:ticker "MSEX"}
   {:ticker "MSFT"}
   {:ticker "MSON"}
   {:ticker "MSTR"}
   {:ticker "MSVB"}
   {:ticker "MTBC"}
   {:ticker "MTC"}
   {:ticker "MTCH"}
   {:ticker "MTCR"}
   {:ticker "MTEM"}
   {:ticker "MTEX"}
   {:ticker "MTLS"}
   {:ticker "MTP"}
   {:ticker "MTRX"}
   {:ticker "MTSC"}
   {:ticker "MTSI"}
   {:ticker "MTSL"}
   {:ticker "MU"}
   {:ticker "MVBF"}
   {:ticker "MVIS"}
   {:ticker "MWK"}
   {:ticker "MXIM"}
   {:ticker "MYFW"}
   {:ticker "MYGN"}
   {:ticker "MYRG"}
   {:ticker "MYSZ"}
   {:ticker "MYT"}
   {:ticker "NAII"}
   {:ticker "NAKD"}
   {:ticker "NAOV"}
   {:ticker "NARI"}
   {:ticker "NATH"}
   {:ticker "NATI"}
   {:ticker "NATR"}
   {:ticker "NAVI"}
   {:ticker "NBAC"}
   {:ticker "NBEV"}
   {:ticker "NBIX"}
   {:ticker "NBLX"}
   {:ticker "NBN"}
   {:ticker "NBRV"}
   {:ticker "NBSE"}
   {:ticker "NBTB"}
   {:ticker "NBTX"}
   {:ticker "NCBS"}
   {:ticker "NCMI"}
   {:ticker "NCNA"}
   {:ticker "NCNO"}
   {:ticker "NCSM"}
   {:ticker "NCTY"}
   {:ticker "NDAQ"}
   {:ticker "NDLS"}
   {:ticker "NDRA"}
   {:ticker "NDSN"}
   {:ticker "NEO"}
   {:ticker "NEOG"}
   {:ticker "NEON"}
   {:ticker "NEOS"}
   {:ticker "NEPH"}
   {:ticker "NEPT"}
   {:ticker "NERV"}
   {:ticker "NESR"}
   {:ticker "NETE"}
   {:ticker "NEWA"}
   {:ticker "NEWT"}
   {:ticker "NEXT"}
   {:ticker "NFBK"}
   {:ticker "NFE"}
   {:ticker "NFLX"}
   {:ticker "NGAC"}
   {:ticker "NGHC"}
   {:ticker "NGM"}
   {:ticker "NGMS"}
   {:ticker "NH"}
   {:ticker "NHIC"}
   {:ticker "NHLD"}
   {:ticker "NHTC"}
   {:ticker "NICE"}
   {:ticker "NICK"}
   {:ticker "NISN"}
   {:ticker "NIU"}
   {:ticker "NK"}
   {:ticker "NKLA"}
   {:ticker "NKSH"}
   {:ticker "NKTR"}
   {:ticker "NKTX"}
   {:ticker "NLOK"}
   {:ticker "NLTX"}
   {:ticker "NMCI"}
   {:ticker "NMFC"}
   {:ticker "NMIH"}
   {:ticker "NMMC"}
   {:ticker "NMRD"}
   {:ticker "NMRK"}
   {:ticker "NMTR"}
   {:ticker "NNBR"}
   {:ticker "NNDM"}
   {:ticker "NNOX"}
   {:ticker "NODK"}
   {:ticker "NOVN"}
   {:ticker "NOVS"}
   {:ticker "NOVT"}
   {:ticker "NPA"}
   {:ticker "NRBO"}
   {:ticker "NRC"}
   {:ticker "NRIM"}
   {:ticker "NRIX"}
   {:ticker "NSEC"}
   {:ticker "NSIT"}
   {:ticker "NSSC"}
   {:ticker "NSTG"}
   {:ticker "NSYS"}
   {:ticker "NTAP"}
   {:ticker "NTCT"}
   {:ticker "NTEC"}
   {:ticker "NTES"}
   {:ticker "NTGR"}
   {:ticker "NTIC"}
   {:ticker "NTLA"}
   {:ticker "NTNX"}
   {:ticker "NTRA"}
   {:ticker "NTRS"}
   {:ticker "NTUS"}
   {:ticker "NTWK"}
   {:ticker "NUAN"}
   {:ticker "NURO"}
   {:ticker "NUVA"}
   {:ticker "NUZE"}
   {:ticker "NVAX"}
   {:ticker "NVCN"}
   {:ticker "NVCR"}
   {:ticker "NVDA"}
   {:ticker "NVEC"}
   {:ticker "NVEE"}
   {:ticker "NVFY"}
   {:ticker "NVIV"}
   {:ticker "NVMI"}
   {:ticker "NVUS"}
   {:ticker "NWBI"}
   {:ticker "NWE"}
   {:ticker "NWFL"}
   {:ticker "NWL"}
   {:ticker "NWLI"}
   {:ticker "NWPX"}
   {:ticker "NWS"}
   {:ticker "NWSA"}
   {:ticker "NXGN"}
   {:ticker "NXPI"}
   {:ticker "NXST"}
   {:ticker "NXTC"}
   {:ticker "NXTD"}
   {:ticker "NYMT"}
   {:ticker "NYMX"}
   {:ticker "OAS"}
   {:ticker "OBAS"}
   {:ticker "OBCI"}
   {:ticker "OBLN"}
   {:ticker "OBNK"}
   {:ticker "OBSV"}
   {:ticker "OCC"}
   {:ticker "OCFC"}
   {:ticker "OCG"}
   {:ticker "OCGN"}
   {:ticker "OCUL"}
   {:ticker "OCUP"}
   {:ticker "ODFL"}
   {:ticker "ODP"}
   {:ticker "ODT"}
   {:ticker "OEG"}
   {:ticker "OESX"}
   {:ticker "OFED"}
   {:ticker "OFIX"}
   {:ticker "OFLX"}
   {:ticker "OGI"}
   {:ticker "OIIM"}
   {:ticker "OKTA"}
   {:ticker "OLB"}
   {:ticker "OLED"}
   {:ticker "OLLI"}
   {:ticker "OLMA"}
   {:ticker "OM"}
   {:ticker "OMAB"}
   {:ticker "OMCL"}
   {:ticker "OMER"}
   {:ticker "OMEX"}
   {:ticker "OMP"}
   {:ticker "ON"}
   {:ticker "ONB"}
   {:ticker "ONCR"}
   {:ticker "ONCS"}
   {:ticker "ONCT"}
   {:ticker "ONCY"}
   {:ticker "ONDS"}
   {:ticker "ONEM"}
   {:ticker "ONEW"}
   {:ticker "ONTX"}
   {:ticker "ONVO"}
   {:ticker "OPBK"}
   {:ticker "OPCH"}
   {:ticker "OPES"}
   {:ticker "OPGN"}
   {:ticker "OPHC"}
   {:ticker "OPI"}
   {:ticker "OPK"}
   {:ticker "OPNT"}
   {:ticker "OPOF"}
   {:ticker "OPRA"}
   {:ticker "OPRT"}
   {:ticker "OPRX"}
   {:ticker "OPT"}
   {:ticker "OPTN"}
   {:ticker "OPTT"}
   {:ticker "ORBC"}
   {:ticker "ORGO"}
   {:ticker "ORGS"}
   {:ticker "ORIC"}
   {:ticker "ORLY"}
   {:ticker "ORMP"}
   {:ticker "ORPH"}
   {:ticker "ORRF"}
   {:ticker "ORTX"}
   {:ticker "OSBC"}
   {:ticker "OSIS"}
   {:ticker "OSMT"}
   {:ticker "OSN"}
   {:ticker "OSPN"}
   {:ticker "OSS"}
   {:ticker "OSTK"}
   {:ticker "OSUR"}
   {:ticker "OSW"}
   {:ticker "OTEL"}
   {:ticker "OTEX"}
   {:ticker "OTIC"}
   {:ticker "OTLK"}
   {:ticker "OTRK"}
   {:ticker "OTTR"}
   {:ticker "OVBC"}
   {:ticker "OVID"}
   {:ticker "OVLY"}
   {:ticker "OXBR"}
   {:ticker "OXFD"}
   {:ticker "OYST"}
   {:ticker "OZK"}
   {:ticker "OZON"}
   {:ticker "PAA"}
   {:ticker "PAAS"}
   {:ticker "PACB"}
   {:ticker "PACW"}
   {:ticker "PAE"}
   {:ticker "PAGP"}
   {:ticker "PAHC"}
   {:ticker "PAIC"}
   {:ticker "PAND"}
   {:ticker "PANL"}
   {:ticker "PASG"}
   {:ticker "PATI"}
   {:ticker "PATK"}
   {:ticker "PAVM"}
   {:ticker "PAYA"}
   {:ticker "PAYS"}
   {:ticker "PAYX"}
   {:ticker "PBCT"}
   {:ticker "PBFS"}
   {:ticker "PBHC"}
   {:ticker "PBIP"}
   {:ticker "PBLA"}
   {:ticker "PBPB"}
   {:ticker "PBTS"}
   {:ticker "PBYI"}
   {:ticker "PCAR"}
   {:ticker "PCB"}
   {:ticker "PCH"}
   {:ticker "PCOM"}
   {:ticker "PCRX"}
   {:ticker "PCSA"}
   {:ticker "PCSB"}
   {:ticker "PCTI"}
   {:ticker "PCTY"}
   {:ticker "PCVX"}
   {:ticker "PCYG"}
   {:ticker "PCYO"}
   {:ticker "PDCE"}
   {:ticker "PDCO"}
   {:ticker "PDD"}
   {:ticker "PDEX"}
   {:ticker "PDFS"}
   {:ticker "PDLB"}
   {:ticker "PDLI"}
   {:ticker "PDSB"}
   {:ticker "PEBK"}
   {:ticker "PEBO"}
   {:ticker "PECK"}
   {:ticker "PEGA"}
   {:ticker "PEIX"}
   {:ticker "PENN"}
   {:ticker "PEP"}
   {:ticker "PERI"}
   {:ticker "PESI"}
   {:ticker "PETQ"}
   {:ticker "PETS"}
   {:ticker "PETZ"}
   {:ticker "PFBC"}
   {:ticker "PFBI"}
   {:ticker "PFC"}
   {:ticker "PFG"}
   {:ticker "PFHD"}
   {:ticker "PFIE"}
   {:ticker "PFIN"}
   {:ticker "PFIS"}
   {:ticker "PFMT"}
   {:ticker "PFPT"}
   {:ticker "PFSW"}
   {:ticker "PGC"}
   {:ticker "PGEN"}
   {:ticker "PGNY"}
   {:ticker "PHAS"}
   {:ticker "PHAT"}
   {:ticker "PHCF"}
   {:ticker "PHIO"}
   {:ticker "PHUN"}
   {:ticker "PI"}
   {:ticker "PICO"}
   {:ticker "PIH"}
   {:ticker "PINC"}
   {:ticker "PIRS"}
   {:ticker "PIXY"}
   {:ticker "PKBK"}
   {:ticker "PKOH"}
   {:ticker "PLAB"}
   {:ticker "PLAY"}
   {:ticker "PLBC"}
   {:ticker "PLCE"}
   {:ticker "PLIN"}
   {:ticker "PLL"}
   {:ticker "PLMR"}
   {:ticker "PLPC"}
   {:ticker "PLRX"}
   {:ticker "PLSE"}
   {:ticker "PLUG"}
   {:ticker "PLUS"}
   {:ticker "PLXP"}
   {:ticker "PLXS"}
   {:ticker "PLYA"}
   {:ticker "PMBC"}
   {:ticker "PMD"}
   {:ticker "PME"}
   {:ticker "PMVP"}
   {:ticker "PNBK"}
   {:ticker "PNFP"}
   {:ticker "PNRG"}
   {:ticker "PNTG"}
   {:ticker "POAI"}
   {:ticker "PODD"}
   {:ticker "POLA"}
   {:ticker "POOL"}
   {:ticker "POWI"}
   {:ticker "POWL"}
   {:ticker "POWW"}
   {:ticker "PPBI"}
   {:ticker "PPC"}
   {:ticker "PPD"}
   {:ticker "PPIH"}
   {:ticker "PPSI"}
   {:ticker "PRAA"}
   {:ticker "PRAH"}
   {:ticker "PRAX"}
   {:ticker "PRCP"}
   {:ticker "PRDO"}
   {:ticker "PRFT"}
   {:ticker "PRFX"}
   {:ticker "PRGS"}
   {:ticker "PRGX"}
   {:ticker "PRIM"}
   {:ticker "PRLD"}
   {:ticker "PROF"}
   {:ticker "PROG"}
   {:ticker "PROV"}
   {:ticker "PRPH"}
   {:ticker "PRPL"}
   {:ticker "PRPO"}
   {:ticker "PRQR"}
   {:ticker "PRSC"}
   {:ticker "PRTA"}
   {:ticker "PRTC"}
   {:ticker "PRTH"}
   {:ticker "PRTK"}
   {:ticker "PRTS"}
   {:ticker "PRVB"}
   {:ticker "PRVL"}
   {:ticker "PS"}
   {:ticker "PSAC"}
   {:ticker "PSHG"}
   {:ticker "PSMT"}
   {:ticker "PSNL"}
   {:ticker "PSTI"}
   {:ticker "PSTV"}
   {:ticker "PSTX"}
   {:ticker "PT"}
   {:ticker "PTAC"}
   {:ticker "PTC"}
   {:ticker "PTCT"}
   {:ticker "PTE"}
   {:ticker "PTEN"}
   {:ticker "PTGX"}
   {:ticker "PTI"}
   {:ticker "PTNR"}
   {:ticker "PTON"}
   {:ticker "PTPI"}
   {:ticker "PTRS"}
   {:ticker "PTSI"}
   {:ticker "PTVCA"}
   {:ticker "PTVCB"}
   {:ticker "PTVE"}
   {:ticker "PUBM"}
   {:ticker "PULM"}
   {:ticker "PUYI"}
   {:ticker "PVAC"}
   {:ticker "PVBC"}
   {:ticker "PWFL"}
   {:ticker "PWOD"}
   {:ticker "PXLW"}
   {:ticker "PXS"}
   {:ticker "PYPD"}
   {:ticker "PYPL"}
   {:ticker "PZZA"}
   {:ticker "QADA"}
   {:ticker "QADB"}
   {:ticker "QCOM"}
   {:ticker "QCRH"}
   {:ticker "QDEL"}
   {:ticker "QELL"}
   {:ticker "QFIN"}
   {:ticker "QH"}
   {:ticker "QIWI"}
   {:ticker "QK"}
   {:ticker "QLGN"}
   {:ticker "QLYS"}
   {:ticker "QMCO"}
   {:ticker "QNST"}
   {:ticker "QRHC"}
   {:ticker "QRTEA"}
   {:ticker "QRTEB"}
   {:ticker "QRVO"}
   {:ticker "QTNT"}
   {:ticker "QTRX"}
   {:ticker "QTT"}
   {:ticker "QUIK"}
   {:ticker "QUMU"}
   {:ticker "QURE"}
   {:ticker "RACA"}
   {:ticker "RADA"}
   {:ticker "RADI"}
   {:ticker "RAIL"}
   {:ticker "RAPT"}
   {:ticker "RARE"}
   {:ticker "RAVE"}
   {:ticker "RAVN"}
   {:ticker "RBB"}
   {:ticker "RBBN"}
   {:ticker "RBCAA"}
   {:ticker "RBCN"}
   {:ticker "RBKB"}
   {:ticker "RBNC"}
   {:ticker "RCEL"}
   {:ticker "RCHG"}
   {:ticker "RCII"}
   {:ticker "RCKT"}
   {:ticker "RCKY"}
   {:ticker "RCM"}
   {:ticker "RCMT"}
   {:ticker "RCON"}
   {:ticker "RDCM"}
   {:ticker "RDFN"}
   {:ticker "RDHL"}
   {:ticker "RDI"}
   {:ticker "RDIB"}
   {:ticker "RDNT"}
   {:ticker "RDUS"}
   {:ticker "RDVT"}
   {:ticker "RDWR"}
   {:ticker "REAL"}
   {:ticker "REDU"}
   {:ticker "REED"}
   {:ticker "REFR"}
   {:ticker "REG"}
   {:ticker "REGI"}
   {:ticker "REGN"}
   {:ticker "REKR"}
   {:ticker "RELL"}
   {:ticker "RELV"}
   {:ticker "REPH"}
   {:ticker "REPL"}
   {:ticker "RESN"}
   {:ticker "RETA"}
   {:ticker "RETO"}
   {:ticker "REYN"}
   {:ticker "RFIL"}
   {:ticker "RGCO"}
   {:ticker "RGEN"}
   {:ticker "RGLD"}
   {:ticker "RGLS"}
   {:ticker "RGNX"}
   {:ticker "RGP"}
   {:ticker "RIBT"}
   {:ticker "RICK"}
   {:ticker "RIDE"}
   {:ticker "RIGL"}
   {:ticker "RILY"}
   {:ticker "RIOT"}
   {:ticker "RIVE"}
   {:ticker "RKDA"}
   {:ticker "RLAY"}
   {:ticker "RLMD"}
   {:ticker "RMBI"}
   {:ticker "RMBL"}
   {:ticker "RMBS"}
   {:ticker "RMCF"}
   {:ticker "RMNI"}
   {:ticker "RMR"}
   {:ticker "RMTI"}
   {:ticker "RNA"}
   {:ticker "RNDB"}
   {:ticker "RNET"}
   {:ticker "RNLX"}
   {:ticker "RNST"}
   {:ticker "RNWK"}
   {:ticker "ROAD"}
   {:ticker "ROCH"}
   {:ticker "ROCK"}
   {:ticker "ROIC"}
   {:ticker "ROKU"}
   {:ticker "ROLL"}
   {:ticker "ROOT"}
   {:ticker "ROST"}
   {:ticker "RP"}
   {:ticker "RPAY"}
   {:ticker "RPD"}
   {:ticker "RPRX"}
   {:ticker "RPTX"}
   {:ticker "RRBI"}
   {:ticker "RRGB"}
   {:ticker "RRR"}
   {:ticker "RSSS"}
   {:ticker "RTLR"}
   {:ticker "RUBY"}
   {:ticker "RUHN"}
   {:ticker "RUN"}
   {:ticker "RUSHA"}
   {:ticker "RUSHB"}
   {:ticker "RUTH"}
   {:ticker "RVMD"}
   {:ticker "RVNC"}
   {:ticker "RVPH"}
   {:ticker "RVSB"}
   {:ticker "RWLK"}
   {:ticker "RXT"}
   {:ticker "RYAAY"}
   {:ticker "RYTM"}
   {:ticker "RZLT"}
   {:ticker "SABR"}
   {:ticker "SAFM"}
   {:ticker "SAFT"}
   {:ticker "SAGE"}
   {:ticker "SAIA"}
   {:ticker "SAII"}
   {:ticker "SAL"}
   {:ticker "SALM"}
   {:ticker "SAMA"}
   {:ticker "SAMG"}
   {:ticker "SANM"}
   {:ticker "SANW"}
   {:ticker "SASR"}
   {:ticker "SATS"}
   {:ticker "SAVA"}
   {:ticker "SBAC"}
   {:ticker "SBBP"}
   {:ticker "SBCF"}
   {:ticker "SBFG"}
   {:ticker "SBGI"}
   {:ticker "SBLK"}
   {:ticker "SBNY"}
   {:ticker "SBRA"}
   {:ticker "SBSI"}
   {:ticker "SBT"}
   {:ticker "SBTX"}
   {:ticker "SBUX"}
   {:ticker "SCHL"}
   {:ticker "SCHN"}
   {:ticker "SCKT"}
   {:ticker "SCOR"}
   {:ticker "SCPH"}
   {:ticker "SCPL"}
   {:ticker "SCSC"}
   {:ticker "SCVL"}
   {:ticker "SCWX"}
   {:ticker "SCYX"}
   {:ticker "SDC"}
   {:ticker "SDGR"}
   {:ticker "SEAC"}
   {:ticker "SECO"}
   {:ticker "SEDG"}
   {:ticker "SEED"}
   {:ticker "SEEL"}
   {:ticker "SEER"}
   {:ticker "SEIC"}
   {:ticker "SELB"}
   {:ticker "SELF"}
   {:ticker "SENEA"}
   {:ticker "SENEB"}
   {:ticker "SESN"}
   {:ticker "SFBC"}
   {:ticker "SFBS"}
   {:ticker "SFET"}
   {:ticker "SFIX"}
   {:ticker "SFM"}
   {:ticker "SFNC"}
   {:ticker "SFST"}
   {:ticker "SFT"}
   {:ticker "SG"}
   {:ticker "SGA"}
   {:ticker "SGAM"}
   {:ticker "SGBX"}
   {:ticker "SGC"}
   {:ticker "SGEN"}
   {:ticker "SGH"}
   {:ticker "SGLB"}
   {:ticker "SGMA"}
   {:ticker "SGMO"}
   {:ticker "SGMS"}
   {:ticker "SGOC"}
   {:ticker "SGRP"}
   {:ticker "SGRY"}
   {:ticker "SGTX"}
   {:ticker "SHBI"}
   {:ticker "SHC"}
   {:ticker "SHEN"}
   {:ticker "SHIP"}
   {:ticker "SHOO"}
   {:ticker "SHSP"}
   {:ticker "SHYF"}
   {:ticker "SIBN"}
   {:ticker "SIC"}
   {:ticker "SIEB"}
   {:ticker "SIEN"}
   {:ticker "SIFY"}
   {:ticker "SIGA"}
   {:ticker "SIGI"}
   {:ticker "SILC"}
   {:ticker "SILK"}
   {:ticker "SIMO"}
   {:ticker "SINA"}
   {:ticker "SINO"}
   {:ticker "SINT"}
   {:ticker "SIOX"}
   {:ticker "SIRI"}
   {:ticker "SITM"}
   {:ticker "SIVB"}
   {:ticker "SJ"}
   {:ticker "SKYW"}
   {:ticker "SLAB"}
   {:ticker "SLCT"}
   {:ticker "SLDB"}
   {:ticker "SLGG"}
   {:ticker "SLGL"}
   {:ticker "SLGN"}
   {:ticker "SLM"}
   {:ticker "SLN"}
   {:ticker "SLNO"}
   {:ticker "SLP"}
   {:ticker "SLRX"}
   {:ticker "SLS"}
   {:ticker "SMBC"}
   {:ticker "SMBK"}
   {:ticker "SMCI"}
   {:ticker "SMED"}
   {:ticker "SMID"}
   {:ticker "SMIT"}
   {:ticker "SMMC"}
   {:ticker "SMMF"}
   {:ticker "SMMT"}
   {:ticker "SMPL"}
   {:ticker "SMSI"}
   {:ticker "SMTC"}
   {:ticker "SMTI"}
   {:ticker "SMTX"}
   {:ticker "SNBR"}
   {:ticker "SNCA"}
   {:ticker "SNCR"}
   {:ticker "SND"}
   {:ticker "SNDE"}
   {:ticker "SNDL"}
   {:ticker "SNDX"}
   {:ticker "SNES"}
   {:ticker "SNEX"}
   {:ticker "SNFCA"}
   {:ticker "SNGX"}
   {:ticker "SNOA"}
   {:ticker "SNPS"}
   {:ticker "SNSS"}
   {:ticker "SNY"}
   {:ticker "SOHO"}
   {:ticker "SOHU"}
   {:ticker "SOLO"}
   {:ticker "SOLY"}
   {:ticker "SONA"}
   {:ticker "SONM"}
   {:ticker "SONN"}
   {:ticker "SONO"}
   {:ticker "SP"}
   {:ticker "SPCB"}
   {:ticker "SPFI"}
   {:ticker "SPI"}
   {:ticker "SPKE"}
   {:ticker "SPLK"}
   {:ticker "SPNE"}
   {:ticker "SPNS"}
   {:ticker "SPOK"}
   {:ticker "SPPI"}
   {:ticker "SPRB"}
   {:ticker "SPRO"}
   {:ticker "SPRT"}
   {:ticker "SPSC"}
   {:ticker "SPT"}
   {:ticker "SPTN"}
   {:ticker "SPWH"}
   {:ticker "SPWR"}
   {:ticker "SQBG"}
   {:ticker "SQFT"}
   {:ticker "SRAC"}
   {:ticker "SRAX"}
   {:ticker "SRCE"}
   {:ticker "SRCL"}
   {:ticker "SRDX"}
   {:ticker "SREV"}
   {:ticker "SRGA"}
   {:ticker "SRNE"}
   {:ticker "SRPT"}
   {:ticker "SRRA"}
   {:ticker "SRRK"}
   {:ticker "SRTS"}
   {:ticker "SSB"}
   {:ticker "SSBI"}
   {:ticker "SSKN"}
   {:ticker "SSNC"}
   {:ticker "SSNT"}
   {:ticker "SSP"}
   {:ticker "SSPK"}
   {:ticker "SSRM"}
   {:ticker "SSTI"}
   {:ticker "SSYS"}
   {:ticker "STAA"}
   {:ticker "STAF"}
   {:ticker "STAY"}
   {:ticker "STBA"}
   {:ticker "STCN"}
   {:ticker "STEP"}
   {:ticker "STFC"}
   {:ticker "STIM"}
   {:ticker "STKL"}
   {:ticker "STKS"}
   {:ticker "STLD"}
   {:ticker "STMP"}
   {:ticker "STND"}
   {:ticker "STNE"}
   {:ticker "STOK"}
   {:ticker "STRA"}
   {:ticker "STRL"}
   {:ticker "STRM"}
   {:ticker "STRO"}
   {:ticker "STRS"}
   {:ticker "STRT"}
   {:ticker "STSA"}
   {:ticker "STTK"}
   {:ticker "STWO"}
   {:ticker "STX"}
   {:ticker "STXB"}
   {:ticker "SUMO"}
   {:ticker "SUMR"}
   {:ticker "SUNW"}
   {:ticker "SUPN"}
   {:ticker "SURF"}
   {:ticker "SV"}
   {:ticker "SVA"}
   {:ticker "SVAC"}
   {:ticker "SVBI"}
   {:ticker "SVC"}
   {:ticker "SVMK"}
   {:ticker "SVRA"}
   {:ticker "SWAV"}
   {:ticker "SWBI"}
   {:ticker "SWIR"}
   {:ticker "SWKH"}
   {:ticker "SWKS"}
   {:ticker "SWTX"}
   {:ticker "SXTC"}
   {:ticker "SY"}
   {:ticker "SYBT"}
   {:ticker "SYBX"}
   {:ticker "SYKE"}
   {:ticker "SYNA"}
   {:ticker "SYNC"}
   {:ticker "SYNH"}
   {:ticker "SYNL"}
   {:ticker "SYPR"}
   {:ticker "SYRS"}
   {:ticker "SYTA"}
   {:ticker "TA"}
   {:ticker "TACO"}
   {:ticker "TACT"}
   {:ticker "TAIT"}
   {:ticker "TANH"}
   {:ticker "TAOP"}
   {:ticker "TARA"}
   {:ticker "TARS"}
   {:ticker "TAST"}
   {:ticker "TATT"}
   {:ticker "TAYD"}
   {:ticker "TBBK"}
   {:ticker "TBIO"}
   {:ticker "TBK"}
   {:ticker "TBLT"}
   {:ticker "TBNK"}
   {:ticker "TBPH"}
   {:ticker "TC"}
   {:ticker "TCBI"}
   {:ticker "TCBK"}
   {:ticker "TCCO"}
   {:ticker "TCDA"}
   {:ticker "TCF"}
   {:ticker "TCFC"}
   {:ticker "TCMD"}
   {:ticker "TCOM"}
   {:ticker "TCON"}
   {:ticker "TCRR"}
   {:ticker "TCX"}
   {:ticker "TDAC"}
   {:ticker "TEAM"}
   {:ticker "TECH"}
   {:ticker "TEDU"}
   {:ticker "TELA"}
   {:ticker "TELL"}
   {:ticker "TENB"}
   {:ticker "TENX"}
   {:ticker "TER"}
   {:ticker "TESS"}
   {:ticker "TFFP"}
   {:ticker "TFSL"}
   {:ticker "TGA"}
   {:ticker "TGLS"}
   {:ticker "TGTX"}
   {:ticker "TH"}
   {:ticker "THBR"}
   {:ticker "THCA"}
   {:ticker "THCB"}
   {:ticker "THFF"}
   {:ticker "THMO"}
   {:ticker "THRM"}
   {:ticker "THRY"}
   {:ticker "THTX"}
   {:ticker "TIG"}
   {:ticker "TIGO"}
   {:ticker "TIGR"}
   {:ticker "TILE"}
   {:ticker "TIPT"}
   {:ticker "TITN"}
   {:ticker "TLC"}
   {:ticker "TLGT"}
   {:ticker "TLMD"}
   {:ticker "TLND"}
   {:ticker "TLRY"}
   {:ticker "TLS"}
   {:ticker "TLSA"}
   {:ticker "TMDI"}
   {:ticker "TMDX"}
   {:ticker "TMTS"}
   {:ticker "TMUS"}
   {:ticker "TNAV"}
   {:ticker "TNDM"}
   {:ticker "TNXP"}
   {:ticker "TOMZ"}
   {:ticker "TOPS"}
   {:ticker "TOTA"}
   {:ticker "TOUR"}
   {:ticker "TOWN"}
   {:ticker "TPCO"}
   {:ticker "TPIC"}
   {:ticker "TPTX"}
   {:ticker "TRCH"}
   {:ticker "TREE"}
   {:ticker "TRHC"}
   {:ticker "TRIB"}
   {:ticker "TRIL"}
   {:ticker "TRIP"}
   {:ticker "TRIT"}
   {:ticker "TRMB"}
   {:ticker "TRMD"}
   {:ticker "TRMK"}
   {:ticker "TRMT"}
   {:ticker "TRNS"}
   {:ticker "TROW"}
   {:ticker "TRS"}
   {:ticker "TRST"}
   {:ticker "TRUE"}
   {:ticker "TRUP"}
   {:ticker "TRVG"}
   {:ticker "TRVI"}
   {:ticker "TRVN"}
   {:ticker "TSBK"}
   {:ticker "TSC"}
   {:ticker "TSCO"}
   {:ticker "TSEM"}
   {:ticker "TSHA"}
   {:ticker "TSLA"}
   {:ticker "TSRI"}
   {:ticker "TTCF"}
   {:ticker "TTD"}
   {:ticker "TTEC"}
   {:ticker "TTEK"}
   {:ticker "TTGT"}
   {:ticker "TTMI"}
   {:ticker "TTNP"}
   {:ticker "TTOO"}
   {:ticker "TTWO"}
   {:ticker "TUSK"}
   {:ticker "TVTX"}
   {:ticker "TVTY"}
   {:ticker "TW"}
   {:ticker "TWCT"}
   {:ticker "TWIN"}
   {:ticker "TWNK"}
   {:ticker "TWOU"}
   {:ticker "TWST"}
   {:ticker "TXG"}
   {:ticker "TXMD"}
   {:ticker "TXN"}
   {:ticker "TXRH"}
   {:ticker "TYHT"}
   {:ticker "TYME"}
   {:ticker "TZOO"}
   {:ticker "UAL"}
   {:ticker "UBCP"}
   {:ticker "UBFO"}
   {:ticker "UBOH"}
   {:ticker "UBSI"}
   {:ticker "UBX"}
   {:ticker "UCBI"}
   {:ticker "UCL"}
   {:ticker "UCTT"}
   {:ticker "UEIC"}
   {:ticker "UEPS"}
   {:ticker "UFCS"}
   {:ticker "UFPI"}
   {:ticker "UFPT"}
   {:ticker "UG"}
   {:ticker "UHAL"}
   {:ticker "UIHC"}
   {:ticker "UK"}
   {:ticker "ULBI"}
   {:ticker "ULH"}
   {:ticker "ULTA"}
   {:ticker "UMBF"}
   {:ticker "UMPQ"}
   {:ticker "UNAM"}
   {:ticker "UNB"}
   {:ticker "UNIT"}
   {:ticker "UNTY"}
   {:ticker "UONE"}
   {:ticker "UONEK"}
   {:ticker "UPLD"}
   {:ticker "UPWK"}
   {:ticker "URBN"}
   {:ticker "URGN"}
   {:ticker "UROV"}
   {:ticker "USAK"}
   {:ticker "USAP"}
   {:ticker "USAT"}
   {:ticker "USAU"}
   {:ticker "USCR"}
   {:ticker "USEG"}
   {:ticker "USIO"}
   {:ticker "USLM"}
   {:ticker "USWS"}
   {:ticker "UTHR"}
   {:ticker "UTMD"}
   {:ticker "UTSI"}
   {:ticker "UVSP"}
   {:ticker "UXIN"}
   {:ticker "VACQ"}
   {:ticker "VALU"}
   {:ticker "VBFC"}
   {:ticker "VBIV"}
   {:ticker "VBLT"}
   {:ticker "VBTX"}
   {:ticker "VC"}
   {:ticker "VCEL"}
   {:ticker "VCNX"}
   {:ticker "VCTR"}
   {:ticker "VCYT"}
   {:ticker "VECO"}
   {:ticker "VEON"}
   {:ticker "VERB"}
   {:ticker "VERI"}
   {:ticker "VERO"}
   {:ticker "VERU"}
   {:ticker "VERX"}
   {:ticker "VERY"}
   {:ticker "VFF"}
   {:ticker "VG"}
   {:ticker "VIAC"}
   {:ticker "VIACA"}
   {:ticker "VIAV"}
   {:ticker "VICR"}
   {:ticker "VIE"}
   {:ticker "VIH"}
   {:ticker "VIOT"}
   {:ticker "VIR"}
   {:ticker "VIRC"}
   {:ticker "VIRT"}
   {:ticker "VISL"}
   {:ticker "VITL"}
   {:ticker "VIVE"}
   {:ticker "VIVO"}
   {:ticker "VJET"}
   {:ticker "VKTX"}
   {:ticker "VLDR"}
   {:ticker "VLGEA"}
   {:ticker "VLY"}
   {:ticker "VMAC"}
   {:ticker "VMAR"}
   {:ticker "VMD"}
   {:ticker "VNDA"}
   {:ticker "VNET"}
   {:ticker "VNOM"}
   {:ticker "VOD"}
   {:ticker "VOXX"}
   {:ticker "VRA"}
   {:ticker "VRAY"}
   {:ticker "VRCA"}
   {:ticker "VREX"}
   {:ticker "VRM"}
   {:ticker "VRME"}
   {:ticker "VRNA"}
   {:ticker "VRNS"}
   {:ticker "VRNT"}
   {:ticker "VRRM"}
   {:ticker "VRSK"}
   {:ticker "VRSN"}
   {:ticker "VRTS"}
   {:ticker "VRTU"}
   {:ticker "VRTX"}
   {:ticker "VSAT"}
   {:ticker "VSEC"}
   {:ticker "VSPR"}
   {:ticker "VSTA"}
   {:ticker "VSTM"}
   {:ticker "VTGN"}
   {:ticker "VTNR"}
   {:ticker "VTRS"}
   {:ticker "VTRU"}
   {:ticker "VTSI"}
   {:ticker "VTVT"}
   {:ticker "VUZI"}
   {:ticker "VVOS"}
   {:ticker "VVPR"}
   {:ticker "VXRT"}
   {:ticker "VYGR"}
   {:ticker "VYNE"}
   {:ticker "WABC"}
   {:ticker "WAFD"}
   {:ticker "WAFU"}
   {:ticker "WASH"}
   {:ticker "WATT"}
   {:ticker "WB"}
   {:ticker "WBA"}
   {:ticker "WDAY"}
   {:ticker "WDC"}
   {:ticker "WDFC"}
   {:ticker "WEN"}
   {:ticker "WERN"}
   {:ticker "WETF"}
   {:ticker "WEYS"}
   {:ticker "WHLM"}
   {:ticker "WHLR"}
   {:ticker "WIFI"}
   {:ticker "WILC"}
   {:ticker "WIMI"}
   {:ticker "WINA"}
   {:ticker "WING"}
   {:ticker "WINT"}
   {:ticker "WIRE"}
   {:ticker "WISA"}
   {:ticker "WIX"}
   {:ticker "WKEY"}
   {:ticker "WKHS"}
   {:ticker "WLDN"}
   {:ticker "WLFC"}
   {:ticker "WLTW"}
   {:ticker "WMG"}
   {:ticker "WNEB"}
   {:ticker "WNW"}
   {:ticker "WORX"}
   {:ticker "WPRT"}
   {:ticker "WRAP"}
   {:ticker "WRLD"}
   {:ticker "WSBC"}
   {:ticker "WSBF"}
   {:ticker "WSC"}
   {:ticker "WSFS"}
   {:ticker "WSG"}
   {:ticker "WSTG"}
   {:ticker "WTBA"}
   {:ticker "WTER"}
   {:ticker "WTFC"}
   {:ticker "WTRE"}
   {:ticker "WTRH"}
   {:ticker "WVE"}
   {:ticker "WVFC"}
   {:ticker "WVVI"}
   {:ticker "WW"}
   {:ticker "WWD"}
   {:ticker "WWR"}
   {:ticker "WYNN"}
   {:ticker "XAIR"}
   {:ticker "XBIO"}
   {:ticker "XBIT"}
   {:ticker "XCUR"}
   {:ticker "XEL"}
   {:ticker "XELA"}
   {:ticker "XELB"}
   {:ticker "XENE"}
   {:ticker "XENT"}
   {:ticker "XERS"}
   {:ticker "XFOR"}
   {:ticker "XGN"}
   {:ticker "XLNX"}
   {:ticker "XLRN"}
   {:ticker "XNCR"}
   {:ticker "XNET"}
   {:ticker "XOMA"}
   {:ticker "XONE"}
   {:ticker "XP"}
   {:ticker "XPEL"}
   {:ticker "XPER"}
   {:ticker "XRAY"}
   {:ticker "XSPA"}
   {:ticker "XTLB"}
   {:ticker "YGMZ"}
   {:ticker "YI"}
   {:ticker "YJ"}
   {:ticker "YMAB"}
   {:ticker "YNDX"}
   {:ticker "YORW"}
   {:ticker "YQ"}
   {:ticker "YRCW"}
   {:ticker "YSAC"}
   {:ticker "YTEN"}
   {:ticker "YTRA"}
   {:ticker "YVR"}
   {:ticker "YY"}
   {:ticker "Z"}
   {:ticker "ZAGG"}
   {:ticker "ZBRA"}
   {:ticker "ZCMD"}
   {:ticker "ZEAL"}
   {:ticker "ZEUS"}
   {:ticker "ZG"}
   {:ticker "ZGNX"}
   {:ticker "ZGYH"}
   {:ticker "ZI"}
   {:ticker "ZION"}
   {:ticker "ZIOP"}
   {:ticker "ZIXI"}
   {:ticker "ZKIN"}
   {:ticker "ZLAB"}
   {:ticker "ZM"}
   {:ticker "ZNGA"}
   {:ticker "ZNTL"}
   {:ticker "ZS"}
   {:ticker "ZSAN"}
   {:ticker "ZUMZ"}
   {:ticker "ZVO"}
   {:ticker "ZYNE"}
   {:ticker "ZYXI"}])
