(ns demo.commons.intrinio.indices.spx)

(def index
  [{:ticker "MMM"}
   {:ticker "AOS"}
   {:ticker "ABT"}
   {:ticker "ABBV"}
   {:ticker "ABMD"}
   {:ticker "ACN"}
   {:ticker "ATVI"}
   {:ticker "ADBE"}
   {:ticker "AAP"}
   {:ticker "AMD"}
   {:ticker "AES"}
   {:ticker "AFL"}
   {:ticker "A"}
   {:ticker "APD"}
   {:ticker "AKAM"}
   {:ticker "ALK"}
   {:ticker "ALB"}
   {:ticker "ARE"}
   {:ticker "ALXN"}
   {:ticker "ALGN"}
   {:ticker "ALLE"}
   {:ticker "LNT"}
   {:ticker "ALL"}
   {:ticker "GOOGL"}
   {:ticker "GOOG"}
   {:ticker "MO"}
   {:ticker "AMZN"}
   {:ticker "AMCR"}
   {:ticker "AEE"}
   {:ticker "AAL"}
   {:ticker "AEP"}
   {:ticker "AXP"}
   {:ticker "AIG"}
   {:ticker "AMT"}
   {:ticker "AWK"}
   {:ticker "AMP"}
   {:ticker "ABC"}
   {:ticker "AME"}
   {:ticker "AMGN"}
   {:ticker "APH"}
   {:ticker "ADI"}
   {:ticker "ANSS"}
   {:ticker "ANTM"}
   {:ticker "AON"}
   {:ticker "APA"}
   {:ticker "AIV"}
   {:ticker "AAPL"}
   {:ticker "AMAT"}
   {:ticker "APTV"}
   {:ticker "ADM"}
   {:ticker "ANET"}
   {:ticker "AJG"}
   {:ticker "AIZ"}
   {:ticker "T"}
   {:ticker "ATO"}
   {:ticker "ADSK"}
   {:ticker "ADP"}
   {:ticker "AZO"}
   {:ticker "AVB"}
   {:ticker "AVY"}
   {:ticker "BKR"}
   {:ticker "BLL"}
   {:ticker "BAC"}
   {:ticker "BAX"}
   {:ticker "BDX"}
   {:ticker "BRK.B"}
   {:ticker "BBY"}
   {:ticker "BIO"}
   {:ticker "BIIB"}
   {:ticker "BLK"}
   {:ticker "BA"}
   {:ticker "BKNG"}
   {:ticker "BWA"}
   {:ticker "BXP"}
   {:ticker "BSX"}
   {:ticker "BMY"}
   {:ticker "AVGO"}
   {:ticker "BR"}
   {:ticker "BF.B"}
   {:ticker "CHRW"}
   {:ticker "COG"}
   {:ticker "CDNS"}
   {:ticker "CPB"}
   {:ticker "COF"}
   {:ticker "CAH"}
   {:ticker "KMX"}
   {:ticker "CCL"}
   {:ticker "CARR"}
   {:ticker "CAT"}
   {:ticker "CBOE"}
   {:ticker "CBRE"}
   {:ticker "CDW"}
   {:ticker "CE"}
   {:ticker "CNC"}
   {:ticker "CNP"}
   {:ticker "CTL"}
   {:ticker "CERN"}
   {:ticker "CF"}
   {:ticker "SCHW"}
   {:ticker "CHTR"}
   {:ticker "CVX"}
   {:ticker "CMG"}
   {:ticker "CB"}
   {:ticker "CHD"}
   {:ticker "CI"}
   {:ticker "CINF"}
   {:ticker "CTAS"}
   {:ticker "CSCO"}
   {:ticker "C"}
   {:ticker "CFG"}
   {:ticker "CTXS"}
   {:ticker "CME"}
   {:ticker "CMS"}
   {:ticker "KO"}
   {:ticker "CTSH"}
   {:ticker "CL"}
   {:ticker "CMCSA"}
   {:ticker "CMA"}
   {:ticker "CAG"}
   {:ticker "CXO"}
   {:ticker "COP"}
   {:ticker "ED"}
   {:ticker "STZ"}
   {:ticker "CPRT"}
   {:ticker "GLW"}
   {:ticker "CTVA"}
   {:ticker "COST"}
   {:ticker "COTY"}
   {:ticker "CCI"}
   {:ticker "CSX"}
   {:ticker "CMI"}
   {:ticker "CVS"}
   {:ticker "DHI"}
   {:ticker "DHR"}
   {:ticker "DRI"}
   {:ticker "DVA"}
   {:ticker "DE"}
   {:ticker "DAL"}
   {:ticker "XRAY"}
   {:ticker "DVN"}
   {:ticker "DXCM"}
   {:ticker "FANG"}
   {:ticker "DLR"}
   {:ticker "DFS"}
   {:ticker "DISCA"}
   {:ticker "DISCK"}
   {:ticker "DISH"}
   {:ticker "DG"}
   {:ticker "DLTR"}
   {:ticker "D"}
   {:ticker "DPZ"}
   {:ticker "DOV"}
   {:ticker "DOW"}
   {:ticker "DTE"}
   {:ticker "DUK"}
   {:ticker "DRE"}
   {:ticker "DD"}
   {:ticker "DXC"}
   {:ticker "ETFC"}
   {:ticker "EMN"}
   {:ticker "ETN"}
   {:ticker "EBAY"}
   {:ticker "ECL"}
   {:ticker "EIX"}
   {:ticker "EW"}
   {:ticker "EA"}
   {:ticker "EMR"}
   {:ticker "ETR"}
   {:ticker "EOG"}
   {:ticker "EFX"}
   {:ticker "EQIX"}
   {:ticker "EQR"}
   {:ticker "ESS"}
   {:ticker "EL"}
   {:ticker "RE"}
   {:ticker "EVRG"}
   {:ticker "ES"}
   {:ticker "EXC"}
   {:ticker "EXPE"}
   {:ticker "EXPD"}
   {:ticker "EXR"}
   {:ticker "XOM"}
   {:ticker "FFIV"}
   {:ticker "FB"}
   {:ticker "FAST"}
   {:ticker "FRT"}
   {:ticker "FDX"}
   {:ticker "FIS"}
   {:ticker "FITB"}
   {:ticker "FRC"}
   {:ticker "FE"}
   {:ticker "FISV"}
   {:ticker "FLT"}
   {:ticker "FLIR"}
   {:ticker "FLS"}
   {:ticker "FMC"}
   {:ticker "F"}
   {:ticker "FTNT"}
   {:ticker "FTV"}
   {:ticker "FBHS"}
   {:ticker "FOXA"}
   {:ticker "FOX"}
   {:ticker "BEN"}
   {:ticker "FCX"}
   {:ticker "GPS"}
   {:ticker "GRMN"}
   {:ticker "IT"}
   {:ticker "GD"}
   {:ticker "GE"}
   {:ticker "GIS"}
   {:ticker "GM"}
   {:ticker "GPC"}
   {:ticker "GILD"}
   {:ticker "GPN"}
   {:ticker "GL"}
   {:ticker "GS"}
   {:ticker "GWW"}
   {:ticker "HRB"}
   {:ticker "HAL"}
   {:ticker "HBI"}
   {:ticker "HIG"}
   {:ticker "HAS"}
   {:ticker "HCA"}
   {:ticker "PEAK"}
   {:ticker "HSIC"}
   {:ticker "HES"}
   {:ticker "HPE"}
   {:ticker "HLT"}
   {:ticker "HFC"}
   {:ticker "HOLX"}
   {:ticker "HD"}
   {:ticker "HON"}
   {:ticker "HRL"}
   {:ticker "HST"}
   {:ticker "HWM"}
   {:ticker "HPQ"}
   {:ticker "HUM"}
   {:ticker "HBAN"}
   {:ticker "HII"}
   {:ticker "IEX"}
   {:ticker "IDXX"}
   {:ticker "INFO"}
   {:ticker "ITW"}
   {:ticker "ILMN"}
   {:ticker "INCY"}
   {:ticker "IR"}
   {:ticker "INTC"}
   {:ticker "ICE"}
   {:ticker "IBM"}
   {:ticker "IFF"}
   {:ticker "IP"}
   {:ticker "IPG"}
   {:ticker "INTU"}
   {:ticker "ISRG"}
   {:ticker "IVZ"}
   {:ticker "IPGP"}
   {:ticker "IQV"}
   {:ticker "IRM"}
   {:ticker "JBHT"}
   {:ticker "JKHY"}
   {:ticker "J"}
   {:ticker "SJM"}
   {:ticker "JNJ"}
   {:ticker "JCI"}
   {:ticker "JPM"}
   {:ticker "JNPR"}
   {:ticker "KSU"}
   {:ticker "K"}
   {:ticker "KEY"}
   {:ticker "KEYS"}
   {:ticker "KMB"}
   {:ticker "KIM"}
   {:ticker "KMI"}
   {:ticker "KLAC"}
   {:ticker "KSS"}
   {:ticker "KHC"}
   {:ticker "KR"}
   {:ticker "LB"}
   {:ticker "LHX"}
   {:ticker "LH"}
   {:ticker "LRCX"}
   {:ticker "LW"}
   {:ticker "LVS"}
   {:ticker "LEG"}
   {:ticker "LDOS"}
   {:ticker "LEN"}
   {:ticker "LLY"}
   {:ticker "LNC"}
   {:ticker "LIN"}
   {:ticker "LYV"}
   {:ticker "LKQ"}
   {:ticker "LMT"}
   {:ticker "L"}
   {:ticker "LOW"}
   {:ticker "LYB"}
   {:ticker "MTB"}
   {:ticker "MRO"}
   {:ticker "MPC"}
   {:ticker "MKTX"}
   {:ticker "MAR"}
   {:ticker "MMC"}
   {:ticker "MLM"}
   {:ticker "MAS"}
   {:ticker "MA"}
   {:ticker "MXIM"}
   {:ticker "MKC"}
   {:ticker "MCD"}
   {:ticker "MCK"}
   {:ticker "MDT"}
   {:ticker "MRK"}
   {:ticker "MET"}
   {:ticker "MTD"}
   {:ticker "MGM"}
   {:ticker "MCHP"}
   {:ticker "MU"}
   {:ticker "MSFT"}
   {:ticker "MAA"}
   {:ticker "MHK"}
   {:ticker "TAP"}
   {:ticker "MDLZ"}
   {:ticker "MNST"}
   {:ticker "MCO"}
   {:ticker "MS"}
   {:ticker "MSI"}
   {:ticker "MSCI"}
   {:ticker "MYL"}
   {:ticker "NDAQ"}
   {:ticker "NOV"}
   {:ticker "NTAP"}
   {:ticker "NFLX"}
   {:ticker "NWL"}
   {:ticker "NEM"}
   {:ticker "NWSA"}
   {:ticker "NWS"}
   {:ticker "NEE"}
   {:ticker "NLSN"}
   {:ticker "NKE"}
   {:ticker "NI"}
   {:ticker "NBL"}
   {:ticker "NSC"}
   {:ticker "NTRS"}
   {:ticker "NOC"}
   {:ticker "NLOK"}
   {:ticker "NCLH"}
   {:ticker "NRG"}
   {:ticker "NUE"}
   {:ticker "NVDA"}
   {:ticker "NVR"}
   {:ticker "ORLY"}
   {:ticker "OXY"}
   {:ticker "ODFL"}
   {:ticker "OMC"}
   {:ticker "OKE"}
   {:ticker "ORCL"}
   {:ticker "OTIS"}
   {:ticker "PCAR"}
   {:ticker "PKG"}
   {:ticker "PH"}
   {:ticker "PAYX"}
   {:ticker "PAYC"}
   {:ticker "PYPL"}
   {:ticker "PNR"}
   {:ticker "PBCT"}
   {:ticker "PEP"}
   {:ticker "PKI"}
   {:ticker "PRGO"}
   {:ticker "PFE"}
   {:ticker "PM"}
   {:ticker "PSX"}
   {:ticker "PNW"}
   {:ticker "PXD"}
   {:ticker "PNC"}
   {:ticker "PPG"}
   {:ticker "PPL"}
   {:ticker "PFG"}
   {:ticker "PG"}
   {:ticker "PGR"}
   {:ticker "PLD"}
   {:ticker "PRU"}
   {:ticker "PEG"}
   {:ticker "PSA"}
   {:ticker "PHM"}
   {:ticker "PVH"}
   {:ticker "QRVO"}
   {:ticker "QCOM"}
   {:ticker "PWR"}
   {:ticker "DGX"}
   {:ticker "RL"}
   {:ticker "RJF"}
   {:ticker "RTX"}
   {:ticker "O"}
   {:ticker "REG"}
   {:ticker "REGN"}
   {:ticker "RF"}
   {:ticker "RSG"}
   {:ticker "RMD"}
   {:ticker "RHI"}
   {:ticker "ROK"}
   {:ticker "ROL"}
   {:ticker "ROP"}
   {:ticker "ROST"}
   {:ticker "RCL"}
   {:ticker "SPGI"}
   {:ticker "CRM"}
   {:ticker "SBAC"}
   {:ticker "SLB"}
   {:ticker "STX"}
   {:ticker "SEE"}
   {:ticker "SRE"}
   {:ticker "NOW"}
   {:ticker "SHW"}
   {:ticker "SPG"}
   {:ticker "SWKS"}
   {:ticker "SLG"}
   {:ticker "SNA"}
   {:ticker "SO"}
   {:ticker "LUV"}
   {:ticker "SWK"}
   {:ticker "SBUX"}
   {:ticker "STT"}
   {:ticker "STE"}
   {:ticker "SYK"}
   {:ticker "SIVB"}
   {:ticker "SYF"}
   {:ticker "SNPS"}
   {:ticker "SYY"}
   {:ticker "TMUS"}
   {:ticker "TROW"}
   {:ticker "TTWO"}
   {:ticker "TPR"}
   {:ticker "TGT"}
   {:ticker "TEL"}
   {:ticker "FTI"}
   {:ticker "TDY"}
   {:ticker "TFX"}
   {:ticker "TXN"}
   {:ticker "TXT"}
   {:ticker "BK"}
   {:ticker "CLX"}
   {:ticker "COO"}
   {:ticker "HSY"}
   {:ticker "MOS"}
   {:ticker "TRV"}
   {:ticker "DIS"}
   {:ticker "TMO"}
   {:ticker "TIF"}
   {:ticker "TJX"}
   {:ticker "TSCO"}
   {:ticker "TT"}
   {:ticker "TDG"}
   {:ticker "TFC"}
   {:ticker "TWTR"}
   {:ticker "TYL"}
   {:ticker "TSN"}
   {:ticker "USB"}
   {:ticker "UDR"}
   {:ticker "ULTA"}
   {:ticker "UAA"}
   {:ticker "UA"}
   {:ticker "UNP"}
   {:ticker "UAL"}
   {:ticker "UNH"}
   {:ticker "UPS"}
   {:ticker "URI"}
   {:ticker "UHS"}
   {:ticker "UNM"}
   {:ticker "VLO"}
   {:ticker "VAR"}
   {:ticker "VTR"}
   {:ticker "VRSN"}
   {:ticker "VRSK"}
   {:ticker "VZ"}
   {:ticker "VRTX"}
   {:ticker "VFC"}
   {:ticker "VIAC"}
   {:ticker "V"}
   {:ticker "VNO"}
   {:ticker "VMC"}
   {:ticker "WRB"}
   {:ticker "WAB"}
   {:ticker "WBA"}
   {:ticker "WMT"}
   {:ticker "WM"}
   {:ticker "WAT"}
   {:ticker "WEC"}
   {:ticker "WFC"}
   {:ticker "WELL"}
   {:ticker "WST"}
   {:ticker "WDC"}
   {:ticker "WU"}
   {:ticker "WRK"}
   {:ticker "WY"}
   {:ticker "WHR"}
   {:ticker "WMB"}
   {:ticker "WLTW"}
   {:ticker "WYNN"}
   {:ticker "XEL"}
   {:ticker "XRX"}
   {:ticker "XLNX"}
   {:ticker "XYL"}
   {:ticker "YUM"}
   {:ticker "ZBRA"}
   {:ticker "ZBH"}
   {:ticker "ZION"}
   {:ticker "ZTS"}])
